-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [protocol]: function definitions
import Aeneas
import Protocol.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace protocol

/-- [protocol::ascii::push_bytes]: loop body 0:
    Source: 'crates/protocol/src/ascii.rs', lines 5:4-8:5
    Visibility: public -/
@[rust_loop_body]
def ascii.push_bytes_loop.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let out1 ← alloc.vec.Vec.push out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [protocol::ascii::push_bytes]: loop 0:
    Source: 'crates/protocol/src/ascii.rs', lines 5:4-8:5
    Visibility: public -/
@[rust_loop]
def ascii.push_bytes_loop
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => ascii.push_bytes_loop.body bytes out1 i1)
    (out, i)

/-- [protocol::ascii::push_bytes]:
    Source: 'crates/protocol/src/ascii.rs', lines 3:0-9:1
    Visibility: public -/
@[reducible]
def ascii.push_bytes
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  ascii.push_bytes_loop out bytes 0#usize

/-- [protocol::ascii::push_range]: loop body 0:
    Source: 'crates/protocol/src/ascii.rs', lines 14:4-17:5
    Visibility: public -/
@[rust_loop_body]
def ascii.push_range_loop.body
  (bytes : Slice Std.U8) («end» : Std.Usize) (out : alloc.vec.Vec Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < «end»
  then
    let i1 ← Slice.index_usize bytes i
    let out1 ← alloc.vec.Vec.push out i1
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [protocol::ascii::push_range]: loop 0:
    Source: 'crates/protocol/src/ascii.rs', lines 14:4-17:5
    Visibility: public -/
@[rust_loop]
def ascii.push_range_loop
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) («end» : Std.Usize)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => ascii.push_range_loop.body bytes «end» out1 i1)
    (out, i)

/-- [protocol::ascii::push_range]:
    Source: 'crates/protocol/src/ascii.rs', lines 12:0-18:1
    Visibility: public -/
@[reducible]
def ascii.push_range
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) (start : Std.Usize)
  («end» : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  ascii.push_range_loop out bytes «end» start

/-- [protocol::ascii::push_decimal]:
    Source: 'crates/protocol/src/ascii.rs', lines 21:0-26:1
    Visibility: public -/
def ascii.push_decimal
  (out : alloc.vec.Vec Std.U8) (n : Std.U32) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ←
    if n >= 10#u32
    then do
         let i ← n / 10#u32
         ascii.push_decimal out i
    else ok out
  let i ← n % 10#u32
  let i1 ← lift (UScalar.cast .U8 i)
  let i2 ← 48#u8 + i1
  alloc.vec.Vec.push out1 i2
partial_fixpoint

/-- [protocol::cell::BYTES_PER_GROUP]
    Source: 'crates/protocol/src/cell.rs', lines 11:0-11:37
    Visibility: public -/
@[global_simps, irreducible] def cell.BYTES_PER_GROUP : Std.Usize := 3#usize

/-- [protocol::cell::CELLS_PER_GROUP]
    Source: 'crates/protocol/src/cell.rs', lines 12:0-12:37
    Visibility: public -/
@[global_simps, irreducible] def cell.CELLS_PER_GROUP : Std.Usize := 8#usize

/-- [protocol::cell::group_bits]:
    Source: 'crates/protocol/src/cell.rs', lines 14:0-16:1 -/
def cell.group_bits
  (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result Std.U32 := do
  let i ← lift (UScalar.cast .U32 a)
  let i1 ← i <<< 16#i32
  let i2 ← lift (UScalar.cast .U32 b)
  let i3 ← i2 <<< 8#i32
  let i4 ← lift (i1 ||| i3)
  let i5 ← lift (UScalar.cast .U32 c)
  ok (i4 ||| i5)

/-- [protocol::cell::cell_at]:
    Source: 'crates/protocol/src/cell.rs', lines 18:0-20:1 -/
def cell.cell_at (bits : Std.U32) (shift : Std.U32) : Result Std.U8 := do
  let i ← bits >>> shift
  let i1 ← lift (i &&& 7#u32)
  ok (UScalar.cast .U8 i1)

/-- [protocol::cell::append_cell]:
    Source: 'crates/protocol/src/cell.rs', lines 22:0-24:1 -/
def cell.append_cell (bits : Std.U32) (cell : Std.U8) : Result Std.U32 := do
  let i ← bits <<< 3#i32
  let i1 ← lift (UScalar.cast .U32 cell)
  ok (i ||| i1)

/-- [protocol::cell::byte_at]:
    Source: 'crates/protocol/src/cell.rs', lines 26:0-28:1 -/
def cell.byte_at (bits : Std.U32) (shift : Std.U32) : Result Std.U8 := do
  let i ← bits >>> shift
  ok (UScalar.cast .U8 i)

/-- [protocol::cell::encode_group]:
    Source: 'crates/protocol/src/cell.rs', lines 32:0-44:1
    Visibility: public -/
def cell.encode_group
  (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result (Array Std.U8 8#usize) := do
  let bits ← cell.group_bits a b c
  let i ← cell.cell_at bits 21#u32
  let i1 ← cell.cell_at bits 18#u32
  let i2 ← cell.cell_at bits 15#u32
  let i3 ← cell.cell_at bits 12#u32
  let i4 ← cell.cell_at bits 9#u32
  let i5 ← cell.cell_at bits 6#u32
  let i6 ← cell.cell_at bits 3#u32
  let i7 ← cell.cell_at bits 0#u32
  ok (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ])

/-- [protocol::cell::decode_group]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 52:4-60:1
    Visibility: public -/
@[rust_loop_body]
def cell.decode_group_loop.body
  (cells : Array Std.U8 8#usize) (bits : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (Option (Array Std.U8 3#usize)))
  := do
  if i < cell.CELLS_PER_GROUP
  then
    let i1 ← Array.index_usize cells i
    if i1 > 7#u8
    then ok (done none)
    else
      let bits1 ← cell.append_cell bits i1
      let i2 ← i + 1#usize
      ok (cont (bits1, i2))
  else
    let i1 ← cell.byte_at bits 16#u32
    let i2 ← cell.byte_at bits 8#u32
    let i3 ← cell.byte_at bits 0#u32
    ok (done (some (Array.make 3#usize [ i1, i2, i3 ])))

/-- [protocol::cell::decode_group]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 52:4-60:1
    Visibility: public -/
@[rust_loop]
def cell.decode_group_loop
  (cells : Array Std.U8 8#usize) (bits : Std.U32) (i : Std.Usize) :
  Result (Option (Array Std.U8 3#usize))
  := do
  loop
    (fun (bits1, i1) => cell.decode_group_loop.body cells bits1 i1)
    (bits, i)

/-- [protocol::cell::decode_group]:
    Source: 'crates/protocol/src/cell.rs', lines 49:0-60:1
    Visibility: public -/
@[reducible]
def cell.decode_group
  (cells : Array Std.U8 8#usize) : Result (Option (Array Std.U8 3#usize)) := do
  cell.decode_group_loop cells 0#u32 0#usize

/-- [protocol::cell::byte_or_zero]:
    Source: 'crates/protocol/src/cell.rs', lines 62:0-64:1 -/
def cell.byte_or_zero
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Std.U8 := do
  let i1 := Slice.len bytes
  if i < i1
  then Slice.index_usize bytes i
  else ok 0#u8

/-- [protocol::cell::push_group]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 68:4-71:5 -/
@[rust_loop_body]
def cell.push_group_loop.body
  (group : Array Std.U8 8#usize) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < cell.CELLS_PER_GROUP
  then
    let i1 ← Array.index_usize group i
    let cells1 ← alloc.vec.Vec.push cells i1
    let i2 ← i + 1#usize
    ok (cont (cells1, i2))
  else ok (done cells)

/-- [protocol::cell::push_group]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 68:4-71:5 -/
@[rust_loop]
def cell.push_group_loop
  (cells : alloc.vec.Vec Std.U8) (group : Array Std.U8 8#usize) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (cells1, i1) => cell.push_group_loop.body group cells1 i1)
    (cells, i)

/-- [protocol::cell::push_group]:
    Source: 'crates/protocol/src/cell.rs', lines 66:0-72:1 -/
@[reducible]
def cell.push_group
  (cells : alloc.vec.Vec Std.U8) (group : Array Std.U8 8#usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  cell.push_group_loop cells group 0#usize

/-- [protocol::cell::encode_cells]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop_body]
def cell.encode_cells_loop.body
  (bytes : Slice Std.U8) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let i3 ← i + 1#usize
    let i4 ← cell.byte_or_zero bytes i3
    let i5 ← i + 2#usize
    let i6 ← cell.byte_or_zero bytes i5
    let group ← cell.encode_group i2 i4 i6
    let cells1 ← cell.push_group cells group
    let i7 ← i + cell.BYTES_PER_GROUP
    ok (cont (cells1, i7))
  else ok (done cells)

/-- [protocol::cell::encode_cells]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop]
def cell.encode_cells_loop
  (bytes : Slice Std.U8) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (cells1, i1) => cell.encode_cells_loop.body bytes cells1 i1)
    (cells, i)

/-- [protocol::cell::encode_cells]:
    Source: 'crates/protocol/src/cell.rs', lines 75:0-88:1
    Visibility: public -/
@[reducible]
def cell.encode_cells
  (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  cell.encode_cells_loop bytes (alloc.vec.Vec.new Std.U8) 0#usize

/-- [protocol::cell::decode_cells]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 99:4-119:1
    Visibility: public -/
@[rust_loop_body]
def cell.decode_cells_loop.body
  (cells : Slice Std.U8) (bytes : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (Option
    (alloc.vec.Vec Std.U8)))
  := do
  let i1 := Slice.len cells
  if i < i1
  then
    let i2 ← Slice.index_usize cells i
    let i3 ← i + 1#usize
    let i4 ← Slice.index_usize cells i3
    let i5 ← i + 2#usize
    let i6 ← Slice.index_usize cells i5
    let i7 ← i + 3#usize
    let i8 ← Slice.index_usize cells i7
    let i9 ← i + 4#usize
    let i10 ← Slice.index_usize cells i9
    let i11 ← i + 5#usize
    let i12 ← Slice.index_usize cells i11
    let i13 ← i + 6#usize
    let i14 ← Slice.index_usize cells i13
    let i15 ← i + 7#usize
    let i16 ← Slice.index_usize cells i15
    let o ←
      cell.decode_group
        (Array.make 8#usize [ i2, i4, i6, i8, i10, i12, i14, i16 ])
    match o with
    | none => ok (done none)
    | some a =>
      let a1 ← Array.index_usize a 0#usize
      let b ← Array.index_usize a 1#usize
      let c ← Array.index_usize a 2#usize
      let bytes1 ← alloc.vec.Vec.push bytes a1
      let bytes2 ← alloc.vec.Vec.push bytes1 b
      let bytes3 ← alloc.vec.Vec.push bytes2 c
      let i17 ← i + cell.CELLS_PER_GROUP
      ok (cont (bytes3, i17))
  else ok (done (some bytes))

/-- [protocol::cell::decode_cells]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 99:4-119:1
    Visibility: public -/
@[rust_loop]
def cell.decode_cells_loop
  (cells : Slice Std.U8) (bytes : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  loop
    (fun (bytes1, i1) => cell.decode_cells_loop.body cells bytes1 i1)
    (bytes, i)

/-- [protocol::cell::decode_cells]:
    Source: 'crates/protocol/src/cell.rs', lines 93:0-119:1
    Visibility: public -/
def cell.decode_cells
  (cells : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let i := Slice.len cells
  let b ← core.num.Usize.is_multiple_of i cell.CELLS_PER_GROUP
  if b
  then cell.decode_cells_loop cells (alloc.vec.Vec.new Std.U8) 0#usize
  else ok none

/-- [protocol::folder::SLASH]
    Source: 'crates/protocol/src/folder.rs', lines 10:0-10:23 -/
@[global_simps, irreducible] def folder.SLASH : Std.U8 := 47#u8

/-- [protocol::folder::end_part]:
    Source: 'crates/protocol/src/folder.rs', lines 20:0-25:1 -/
def folder.end_part
  (parts : alloc.vec.Vec (alloc.vec.Vec Std.U8)) (cur : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec (alloc.vec.Vec Std.U8))
  := do
  let i := alloc.vec.Vec.len cur
  if i > 0#usize
  then alloc.vec.Vec.push parts cur
  else ok parts

/-- [protocol::folder::take_byte]:
    Source: 'crates/protocol/src/folder.rs', lines 27:0-34:1 -/
def folder.take_byte
  (parts : alloc.vec.Vec (alloc.vec.Vec Std.U8)) (cur : alloc.vec.Vec Std.U8)
  (b : Std.U8) :
  Result ((alloc.vec.Vec (alloc.vec.Vec Std.U8)) × (alloc.vec.Vec Std.U8))
  := do
  if b = folder.SLASH
  then let v ← folder.end_part parts cur
       ok (v, alloc.vec.Vec.new Std.U8)
  else let cur1 ← alloc.vec.Vec.push cur b
       ok (parts, cur1)

/-- [protocol::folder::split_parts]: loop body 0:
    Source: 'crates/protocol/src/folder.rs', lines 41:4-46:5 -/
@[rust_loop_body]
def folder.split_parts_loop.body
  (path : Slice Std.U8) (parts : alloc.vec.Vec (alloc.vec.Vec Std.U8))
  (cur : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (alloc.vec.Vec Std.U8)) × (alloc.vec.Vec
    Std.U8) × Std.Usize) ((alloc.vec.Vec (alloc.vec.Vec Std.U8)) ×
    (alloc.vec.Vec Std.U8)))
  := do
  let i1 := Slice.len path
  if i < i1
  then
    let i2 ← Slice.index_usize path i
    let (p, c) ← folder.take_byte parts cur i2
    let i3 ← i + 1#usize
    ok (cont (p, c, i3))
  else ok (done (parts, cur))

/-- [protocol::folder::split_parts]: loop 0:
    Source: 'crates/protocol/src/folder.rs', lines 41:4-46:5 -/
@[rust_loop]
def folder.split_parts_loop
  (path : Slice Std.U8) (parts : alloc.vec.Vec (alloc.vec.Vec Std.U8))
  (cur : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result ((alloc.vec.Vec (alloc.vec.Vec Std.U8)) × (alloc.vec.Vec Std.U8))
  := do
  loop
    (fun (parts1, cur1, i1) => folder.split_parts_loop.body path parts1 cur1
      i1)
    (parts, cur, i)

/-- [protocol::folder::split_parts]:
    Source: 'crates/protocol/src/folder.rs', lines 37:0-48:1 -/
def folder.split_parts
  (path : Slice Std.U8) : Result (alloc.vec.Vec (alloc.vec.Vec Std.U8)) := do
  let (parts, cur) ←
    folder.split_parts_loop path (alloc.vec.Vec.new (alloc.vec.Vec Std.U8))
      (alloc.vec.Vec.new Std.U8) 0#usize
  folder.end_part parts cur

/-- [protocol::folder::is_dot]:
    Source: 'crates/protocol/src/folder.rs', lines 50:0-52:1 -/
def folder.is_dot (part : Slice Std.U8) : Result Bool := do
  let i := Slice.len part
  if i = 1#usize
  then let i1 ← Slice.index_usize part 0#usize
       ok (i1 = 46#u8)
  else ok false

/-- [protocol::folder::is_dot_dot]:
    Source: 'crates/protocol/src/folder.rs', lines 54:0-56:1 -/
def folder.is_dot_dot (part : Slice Std.U8) : Result Bool := do
  let i := Slice.len part
  if i = 2#usize
  then
    let i1 ← Slice.index_usize part 0#usize
    if i1 = 46#u8
    then let i2 ← Slice.index_usize part 1#usize
         ok (i2 = 46#u8)
    else ok false
  else ok false

/-- [protocol::folder::put]:
    Source: 'crates/protocol/src/folder.rs', lines 58:0-65:1 -/
def folder.put
  (stack : alloc.vec.Vec (alloc.vec.Vec Std.U8)) (depth : Std.Usize)
  (part : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec (alloc.vec.Vec Std.U8))
  := do
  let i := alloc.vec.Vec.len stack
  if depth < i
  then
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
        (alloc.vec.Vec Std.U8)) stack depth
    ok (index_mut_back part)
  else alloc.vec.Vec.push stack part

/-- [protocol::seen::copy_bytes]:
    Source: 'crates/protocol/src/seen.rs', lines 49:0-53:1 -/
def seen.copy_bytes
  (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let i := Slice.len bytes
  ascii.push_range (alloc.vec.Vec.new Std.U8) bytes 0#usize i

/-- [protocol::folder::apply_part]:
    Source: 'crates/protocol/src/folder.rs', lines 68:0-92:1 -/
def folder.apply_part
  (walk : folder.Walk) (part : Slice Std.U8) : Result folder.Walk := do
  let b ← folder.is_dot part
  if b
  then ok walk
  else
    let b1 ← folder.is_dot_dot part
    if b1
    then
      if walk.depth = 0#usize
      then ok { walk with ok := false, depth := 0#usize }
      else let i ← walk.depth - 1#usize
           ok { walk with depth := i }
    else
      let v ← seen.copy_bytes part
      let v1 ← folder.put walk.stack walk.depth v
      let i ← walk.depth + 1#usize
      ok { walk with stack := v1, depth := i }

/-- [protocol::folder::apply_all]: loop body 0:
    Source: 'crates/protocol/src/folder.rs', lines 96:4-99:5 -/
@[rust_loop_body]
def folder.apply_all_loop.body
  (parts : Slice (alloc.vec.Vec Std.U8)) (walk : folder.Walk) (i : Std.Usize) :
  Result (ControlFlow (folder.Walk × Std.Usize) (Bool × (alloc.vec.Vec
    (alloc.vec.Vec Std.U8)) × Std.Usize))
  := do
  if walk.ok
  then
    let i1 := Slice.len parts
    if i < i1
    then
      let v ← Slice.index_usize parts i
      let s := alloc.vec.Vec.deref v
      let walk1 ← folder.apply_part walk s
      let i2 ← i + 1#usize
      ok (cont (walk1, i2))
    else ok (done (true, walk.stack, walk.depth))
  else ok (done (false, walk.stack, walk.depth))

/-- [protocol::folder::apply_all]: loop 0:
    Source: 'crates/protocol/src/folder.rs', lines 96:4-99:5 -/
@[rust_loop]
def folder.apply_all_loop
  (walk : folder.Walk) (parts : Slice (alloc.vec.Vec Std.U8)) (i : Std.Usize) :
  Result (Bool × (alloc.vec.Vec (alloc.vec.Vec Std.U8)) × Std.Usize)
  := do
  loop
    (fun (walk1, i1) => folder.apply_all_loop.body parts walk1 i1)
    (walk, i)

/-- [protocol::folder::apply_all]:
    Source: 'crates/protocol/src/folder.rs', lines 94:0-101:1 -/
def folder.apply_all
  (walk : folder.Walk) (parts : Slice (alloc.vec.Vec Std.U8)) :
  Result folder.Walk
  := do
  let (b, v, i) ← folder.apply_all_loop walk parts 0#usize
  ok { ok := b, stack := v, depth := i }

/-- [protocol::folder::start]:
    Source: 'crates/protocol/src/folder.rs', lines 103:0-114:1 -/
def folder.start
  (base : Slice Std.U8) (request : Slice Std.U8) : Result folder.Walk := do
  let i := Slice.len request
  if i > 0#usize
  then
    let i1 ← Slice.index_usize request 0#usize
    if i1 = folder.SLASH
    then
      ok
        {
          ok := true,
          stack := (alloc.vec.Vec.new (alloc.vec.Vec Std.U8)),
          depth := 0#usize
        }
    else
      let v ← folder.split_parts base
      let s := alloc.vec.Vec.deref v
      folder.apply_all
        {
          ok := true,
          stack := (alloc.vec.Vec.new (alloc.vec.Vec Std.U8)),
          depth := 0#usize
        } s
  else
    let v ← folder.split_parts base
    let s := alloc.vec.Vec.deref v
    folder.apply_all
      {
        ok := true,
        stack := (alloc.vec.Vec.new (alloc.vec.Vec Std.U8)),
        depth := 0#usize
      } s

/-- [protocol::seen::bytes_equal]: loop body 0:
    Source: 'crates/protocol/src/seen.rs', lines 29:4-36:1 -/
@[rust_loop_body]
def seen.bytes_equal_loop.body
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len a
  if i < i1
  then
    let i2 ← Slice.index_usize a i
    let i3 ← Slice.index_usize b i
    if i2 != i3
    then ok (done false)
    else let i4 ← i + 1#usize
         ok (cont i4)
  else ok (done true)

/-- [protocol::seen::bytes_equal]: loop 0:
    Source: 'crates/protocol/src/seen.rs', lines 29:4-36:1 -/
@[rust_loop]
def seen.bytes_equal_loop
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => seen.bytes_equal_loop.body a b i1)
    i

/-- [protocol::seen::bytes_equal]:
    Source: 'crates/protocol/src/seen.rs', lines 24:0-36:1 -/
def seen.bytes_equal (a : Slice Std.U8) (b : Slice Std.U8) : Result Bool := do
  let i := Slice.len a
  let i1 := Slice.len b
  if i != i1
  then ok false
  else seen.bytes_equal_loop a b 0#usize

/-- [protocol::folder::is_prefix]: loop body 0:
    Source: 'crates/protocol/src/folder.rs', lines 119:4-122:5 -/
@[rust_loop_body]
def folder.is_prefix_loop.body
  (root : Slice (alloc.vec.Vec Std.U8)) (stack : Slice (alloc.vec.Vec Std.U8))
  (same : Bool) (j : Std.Usize) :
  Result (ControlFlow (Bool × Std.Usize) Bool)
  := do
  if same
  then
    let i := Slice.len root
    if j < i
    then
      let v ← Slice.index_usize root j
      let s := alloc.vec.Vec.deref v
      let v1 ← Slice.index_usize stack j
      let s1 := alloc.vec.Vec.deref v1
      let same1 ← seen.bytes_equal s s1
      let j1 ← j + 1#usize
      ok (cont (same1, j1))
    else ok (done true)
  else ok (done false)

/-- [protocol::folder::is_prefix]: loop 0:
    Source: 'crates/protocol/src/folder.rs', lines 119:4-122:5 -/
@[rust_loop]
def folder.is_prefix_loop
  (root : Slice (alloc.vec.Vec Std.U8)) (stack : Slice (alloc.vec.Vec Std.U8))
  (same : Bool) (j : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (same1, j1) => folder.is_prefix_loop.body root stack same1 j1)
    (same, j)

/-- [protocol::folder::is_prefix]:
    Source: 'crates/protocol/src/folder.rs', lines 116:0-124:1 -/
def folder.is_prefix
  (root : Slice (alloc.vec.Vec Std.U8)) (stack : Slice (alloc.vec.Vec Std.U8))
  (depth : Std.Usize) :
  Result Bool
  := do
  let i := Slice.len root
  folder.is_prefix_loop root stack (i <= depth) 0#usize

/-- [protocol::folder::inside_any]: loop body 0:
    Source: 'crates/protocol/src/folder.rs', lines 129:4-132:5 -/
@[rust_loop_body]
def folder.inside_any_loop.body
  (roots : Slice (alloc.vec.Vec Std.U8)) (stack : Slice (alloc.vec.Vec Std.U8))
  (depth : Std.Usize) (found : Bool) (i : Std.Usize) :
  Result (ControlFlow (Bool × Std.Usize) Bool)
  := do
  if found
  then ok (done true)
  else
    let i1 := Slice.len roots
    if i < i1
    then
      let v ← Slice.index_usize roots i
      let s := alloc.vec.Vec.deref v
      let v1 ← folder.split_parts s
      let s1 := alloc.vec.Vec.deref v1
      let found1 ← folder.is_prefix s1 stack depth
      let i2 ← i + 1#usize
      ok (cont (found1, i2))
    else ok (done false)

/-- [protocol::folder::inside_any]: loop 0:
    Source: 'crates/protocol/src/folder.rs', lines 129:4-132:5 -/
@[rust_loop]
def folder.inside_any_loop
  (roots : Slice (alloc.vec.Vec Std.U8)) (stack : Slice (alloc.vec.Vec Std.U8))
  (depth : Std.Usize) (found : Bool) (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (found1, i1) => folder.inside_any_loop.body roots stack depth found1
      i1)
    (found, i)

/-- [protocol::folder::inside_any]:
    Source: 'crates/protocol/src/folder.rs', lines 126:0-134:1 -/
@[reducible]
def folder.inside_any
  (roots : Slice (alloc.vec.Vec Std.U8)) (stack : Slice (alloc.vec.Vec Std.U8))
  (depth : Std.Usize) :
  Result Bool
  := do
  folder.inside_any_loop roots stack depth false 0#usize

/-- [protocol::folder::join]: loop body 0:
    Source: 'crates/protocol/src/folder.rs', lines 139:4-143:5 -/
@[rust_loop_body]
def folder.join_loop.body
  (stack : Slice (alloc.vec.Vec Std.U8)) (depth : Std.Usize)
  (out : alloc.vec.Vec Std.U8) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if j < depth
  then
    let out1 ← alloc.vec.Vec.push out folder.SLASH
    let v ← Slice.index_usize stack j
    let s := alloc.vec.Vec.deref v
    let out2 ← ascii.push_bytes out1 s
    let j1 ← j + 1#usize
    ok (cont (out2, j1))
  else ok (done out)

/-- [protocol::folder::join]: loop 0:
    Source: 'crates/protocol/src/folder.rs', lines 139:4-143:5 -/
@[rust_loop]
def folder.join_loop
  (stack : Slice (alloc.vec.Vec Std.U8)) (depth : Std.Usize)
  (out : alloc.vec.Vec Std.U8) (j : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, j1) => folder.join_loop.body stack depth out1 j1)
    (out, j)

/-- [protocol::folder::join]:
    Source: 'crates/protocol/src/folder.rs', lines 136:0-145:1 -/
@[reducible]
def folder.join
  (stack : Slice (alloc.vec.Vec Std.U8)) (depth : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  folder.join_loop stack depth (alloc.vec.Vec.new Std.U8) 0#usize

/-- [protocol::folder::resolve_folder]:
    Source: 'crates/protocol/src/folder.rs', lines 150:0-156:1
    Visibility: public -/
def folder.resolve_folder
  (roots : Slice (alloc.vec.Vec Std.U8)) (base : Slice Std.U8)
  (request : Slice Std.U8) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  let w ← folder.start base request
  let v ← folder.split_parts request
  let s := alloc.vec.Vec.deref v
  let walk ← folder.apply_all w s
  if walk.ok
  then
    if walk.depth = 0#usize
    then ok none
    else
      let s1 := alloc.vec.Vec.deref walk.stack
      let b ← folder.inside_any roots s1 walk.depth
      if b
      then
        let s2 := alloc.vec.Vec.deref walk.stack
        let v1 ← folder.join s2 walk.depth
        ok (some v1)
      else ok none
  else ok none

/-- [protocol::frame::MAGIC]
    Source: 'crates/protocol/src/frame.rs', lines 13:0-13:40
    Visibility: public -/
@[global_simps, irreducible]
def frame.MAGIC : Array Std.U8 2#usize := Array.make 2#usize [ 110#u8, 82#u8 ]

/-- [protocol::frame::VERSION]
    Source: 'crates/protocol/src/frame.rs', lines 14:0-14:26
    Visibility: public -/
@[global_simps, irreducible] def frame.VERSION : Std.U8 := 1#u8

/-- [protocol::frame::HEADER_LEN]
    Source: 'crates/protocol/src/frame.rs', lines 15:0-15:33
    Visibility: public -/
@[global_simps, irreducible] def frame.HEADER_LEN : Std.Usize := 11#usize

/-- [protocol::frame::CHECKSUM_LEN]
    Source: 'crates/protocol/src/frame.rs', lines 16:0-16:34
    Visibility: public -/
@[global_simps, irreducible] def frame.CHECKSUM_LEN : Std.Usize := 2#usize

/-- [protocol::frame::TAG_LEN]
    Source: 'crates/protocol/src/frame.rs', lines 17:0-17:29
    Visibility: public -/
@[global_simps, irreducible] def frame.TAG_LEN : Std.Usize := 8#usize

/-- [protocol::frame::MAX_PAYLOAD]
    Source: 'crates/protocol/src/frame.rs', lines 18:0-18:36
    Visibility: public -/
@[global_simps, irreducible] def frame.MAX_PAYLOAD : Std.Usize := 3200#usize

/-- [protocol::frame::MAX_AGE]
    Source: 'crates/protocol/src/frame.rs', lines 21:0-21:29
    Visibility: public -/
@[global_simps, irreducible] def frame.MAX_AGE : Std.U32 := 300#u32

/-- [protocol::frame::MAX_AHEAD]
    Source: 'crates/protocol/src/frame.rs', lines 22:0-22:30
    Visibility: public -/
@[global_simps, irreducible] def frame.MAX_AHEAD : Std.U32 := 60#u32

/-- [protocol::frame::push_be16]:
    Source: 'crates/protocol/src/frame.rs', lines 50:0-53:1 -/
def frame.push_be16
  (out : alloc.vec.Vec Std.U8) (n : Std.U16) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i ← n >>> 8#i32
  let i1 ← lift (UScalar.cast .U8 i)
  let out1 ← alloc.vec.Vec.push out i1
  let i2 ← lift (UScalar.cast .U8 n)
  alloc.vec.Vec.push out1 i2

/-- [protocol::frame::push_be32]:
    Source: 'crates/protocol/src/frame.rs', lines 55:0-60:1 -/
def frame.push_be32
  (out : alloc.vec.Vec Std.U8) (n : Std.U32) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i ← n >>> 24#i32
  let i1 ← lift (UScalar.cast .U8 i)
  let out1 ← alloc.vec.Vec.push out i1
  let i2 ← n >>> 16#i32
  let i3 ← lift (UScalar.cast .U8 i2)
  let out2 ← alloc.vec.Vec.push out1 i3
  let i4 ← n >>> 8#i32
  let i5 ← lift (UScalar.cast .U8 i4)
  let out3 ← alloc.vec.Vec.push out2 i5
  let i6 ← lift (UScalar.cast .U8 n)
  alloc.vec.Vec.push out3 i6

/-- [protocol::frame::read_be16]:
    Source: 'crates/protocol/src/frame.rs', lines 62:0-64:1 -/
def frame.read_be16
  (bytes : Slice Std.U8) («at» : Std.Usize) : Result Std.U16 := do
  let i ← Slice.index_usize bytes «at»
  let i1 ← lift (UScalar.cast .U16 i)
  let i2 ← i1 <<< 8#i32
  let i3 ← «at» + 1#usize
  let i4 ← Slice.index_usize bytes i3
  let i5 ← lift (UScalar.cast .U16 i4)
  ok (i2 ||| i5)

/-- [protocol::frame::read_be32]:
    Source: 'crates/protocol/src/frame.rs', lines 66:0-71:1 -/
def frame.read_be32
  (bytes : Slice Std.U8) («at» : Std.Usize) : Result Std.U32 := do
  let i ← Slice.index_usize bytes «at»
  let i1 ← lift (UScalar.cast .U32 i)
  let i2 ← i1 <<< 24#i32
  let i3 ← «at» + 1#usize
  let i4 ← Slice.index_usize bytes i3
  let i5 ← lift (UScalar.cast .U32 i4)
  let i6 ← i5 <<< 16#i32
  let i7 ← lift (i2 ||| i6)
  let i8 ← «at» + 2#usize
  let i9 ← Slice.index_usize bytes i8
  let i10 ← lift (UScalar.cast .U32 i9)
  let i11 ← i10 <<< 8#i32
  let i12 ← lift (i7 ||| i11)
  let i13 ← «at» + 3#usize
  let i14 ← Slice.index_usize bytes i13
  let i15 ← lift (UScalar.cast .U32 i14)
  ok (i12 ||| i15)

/-- [protocol::frame::fletcher16]: loop body 0:
    Source: 'crates/protocol/src/frame.rs', lines 78:4-82:5 -/
@[rust_loop_body]
def frame.fletcher16_loop.body
  (bytes : Slice Std.U8) («end» : Std.Usize) (s1 : Std.U16) (s2 : Std.U16)
  (i : Std.Usize) :
  Result (ControlFlow (Std.U16 × Std.U16 × Std.Usize) (Std.U16 × Std.U16))
  := do
  if i < «end»
  then
    let i1 ← Slice.index_usize bytes i
    let i2 ← lift (UScalar.cast .U16 i1)
    let i3 ← s1 + i2
    let s11 ← i3 % 255#u16
    let i4 ← s2 + s11
    let s21 ← i4 % 255#u16
    let i5 ← i + 1#usize
    ok (cont (s11, s21, i5))
  else ok (done (s1, s2))

/-- [protocol::frame::fletcher16]: loop 0:
    Source: 'crates/protocol/src/frame.rs', lines 78:4-82:5 -/
@[rust_loop]
def frame.fletcher16_loop
  (bytes : Slice Std.U8) («end» : Std.Usize) (s1 : Std.U16) (s2 : Std.U16)
  (i : Std.Usize) :
  Result (Std.U16 × Std.U16)
  := do
  loop
    (fun (s11, s21, i1) => frame.fletcher16_loop.body bytes «end» s11 s21 i1)
    (s1, s2, i)

/-- [protocol::frame::fletcher16]:
    Source: 'crates/protocol/src/frame.rs', lines 74:0-84:1 -/
def frame.fletcher16
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (Std.U8 × Std.U8)
  := do
  let (s1, s2) ← frame.fletcher16_loop bytes «end» 0#u16 0#u16 start
  let i ← lift (UScalar.cast .U8 s1)
  let i1 ← lift (UScalar.cast .U8 s2)
  ok (i, i1)

/-- [protocol::frame::payload_len]:
    Source: 'crates/protocol/src/frame.rs', lines 87:0-89:1 -/
def frame.payload_len (payload : Slice Std.U8) : Result Std.U16 := do
  let i := Slice.len payload
  ok (UScalar.cast .U16 i)

/-- [protocol::frame::encode_frame]:
    Source: 'crates/protocol/src/frame.rs', lines 93:0-109:1
    Visibility: public -/
def frame.encode_frame
  (time : Std.U32) (frame_id : Std.U16) (payload : Slice Std.U8)
  (tag : Array Std.U8 8#usize) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  let i := Slice.len payload
  if i > frame.MAX_PAYLOAD
  then ok none
  else
    let s ← lift (Array.to_slice frame.MAGIC)
    let out ← ascii.push_bytes (alloc.vec.Vec.new Std.U8) s
    let out1 ← alloc.vec.Vec.push out frame.VERSION
    let out2 ← frame.push_be32 out1 time
    let out3 ← frame.push_be16 out2 frame_id
    let i1 ← frame.payload_len payload
    let out4 ← frame.push_be16 out3 i1
    let out5 ← ascii.push_bytes out4 payload
    let s1 := alloc.vec.Vec.deref out5
    let i2 := alloc.vec.Vec.len out5
    let (s11, s2) ← frame.fletcher16 s1 2#usize i2
    let out6 ← alloc.vec.Vec.push out5 s11
    let out7 ← alloc.vec.Vec.push out6 s2
    let s3 ← lift (Array.to_slice tag)
    let out8 ← ascii.push_bytes out7 s3
    ok (some out8)

/-- [protocol::frame::decode_frame]:
    Source: 'crates/protocol/src/frame.rs', lines 117:0-159:1
    Visibility: public -/
def frame.decode_frame
  (bytes : Slice Std.U8) :
  Result (core.result.Result frame.Frame frame.FrameError)
  := do
  let n := Slice.len bytes
  let i ← frame.HEADER_LEN + frame.CHECKSUM_LEN
  let i1 ← i + frame.TAG_LEN
  if n < i1
  then ok (core.result.Result.Err frame.FrameError.TooShort)
  else
    let i2 ← Slice.index_usize bytes 0#usize
    let i3 ← Array.index_usize frame.MAGIC 0#usize
    if i2 != i3
    then ok (core.result.Result.Err frame.FrameError.BadMagic)
    else
      let i4 ← Slice.index_usize bytes 1#usize
      let i5 ← Array.index_usize frame.MAGIC 1#usize
      if i4 != i5
      then ok (core.result.Result.Err frame.FrameError.BadMagic)
      else
        let i6 ← Slice.index_usize bytes 2#usize
        if i6 != frame.VERSION
        then ok (core.result.Result.Err frame.FrameError.BadVersion)
        else
          let i7 ← frame.read_be16 bytes 9#usize
          let len ← lift (UScalar.cast .Usize i7)
          if len > frame.MAX_PAYLOAD
          then ok (core.result.Result.Err frame.FrameError.TooLong)
          else
            let «end» ← frame.HEADER_LEN + len
            let i8 ← «end» + frame.CHECKSUM_LEN
            let i9 ← i8 + frame.TAG_LEN
            if n < i9
            then ok (core.result.Result.Err frame.FrameError.Truncated)
            else
              let (s1, s2) ← frame.fletcher16 bytes 2#usize «end»
              let i10 ← Slice.index_usize bytes «end»
              if i10 != s1
              then ok (core.result.Result.Err frame.FrameError.BadChecksum)
              else
                let i11 ← «end» + 1#usize
                let i12 ← Slice.index_usize bytes i11
                if i12 != s2
                then ok (core.result.Result.Err frame.FrameError.BadChecksum)
                else
                  let payload ←
                    ascii.push_range (alloc.vec.Vec.new Std.U8) bytes
                      frame.HEADER_LEN «end»
                  let i13 ← Slice.index_usize bytes i8
                  let i14 ← i8 + 1#usize
                  let i15 ← Slice.index_usize bytes i14
                  let i16 ← i8 + 2#usize
                  let i17 ← Slice.index_usize bytes i16
                  let i18 ← i8 + 3#usize
                  let i19 ← Slice.index_usize bytes i18
                  let i20 ← i8 + 4#usize
                  let i21 ← Slice.index_usize bytes i20
                  let i22 ← i8 + 5#usize
                  let i23 ← Slice.index_usize bytes i22
                  let i24 ← i8 + 6#usize
                  let i25 ← Slice.index_usize bytes i24
                  let i26 ← i8 + 7#usize
                  let i27 ← Slice.index_usize bytes i26
                  let i28 ← frame.read_be32 bytes 3#usize
                  let i29 ← frame.read_be16 bytes 7#usize
                  ok (core.result.Result.Ok
                    {
                      time := i28,
                      frame_id := i29,
                      payload,
                      tag :=
                        (Array.make 8#usize [
                          i13, i15, i17, i19, i21, i23, i25, i27
                          ])
                    })

/-- [protocol::frame::signed_len]:
    Source: 'crates/protocol/src/frame.rs', lines 163:0-165:1
    Visibility: public -/
def frame.signed_len (f : frame.Frame) : Result Std.Usize := do
  let i := alloc.vec.Vec.len f.payload
  let i1 ← frame.HEADER_LEN + i
  i1 + frame.CHECKSUM_LEN

/-- [protocol::frame::is_stale]:
    Source: 'crates/protocol/src/frame.rs', lines 168:0-170:1 -/
def frame.is_stale (frame_time : Std.U32) (now : Std.U32) : Result Bool := do
  let i ← lift (UScalar.cast .U64 now)
  let i1 ← lift (UScalar.cast .U64 frame_time)
  let i2 ← lift (UScalar.cast .U64 frame.MAX_AGE)
  let i3 ← i1 + i2
  ok (i > i3)

/-- [protocol::frame::is_ahead]:
    Source: 'crates/protocol/src/frame.rs', lines 172:0-174:1 -/
def frame.is_ahead (frame_time : Std.U32) (now : Std.U32) : Result Bool := do
  let i ← lift (UScalar.cast .U64 frame_time)
  let i1 ← lift (UScalar.cast .U64 now)
  let i2 ← lift (UScalar.cast .U64 frame.MAX_AHEAD)
  let i3 ← i1 + i2
  ok (i > i3)

/-- [protocol::frame::is_fresh]:
    Source: 'crates/protocol/src/frame.rs', lines 177:0-179:1
    Visibility: public -/
def frame.is_fresh (frame_time : Std.U32) (now : Std.U32) : Result Bool := do
  let b ← frame.is_stale frame_time now
  if b
  then ok false
  else let b1 ← frame.is_ahead frame_time now
       ok (¬ b1)

/-- [protocol::frame::check_frame]:
    Source: 'crates/protocol/src/frame.rs', lines 186:0-197:1
    Visibility: public -/
def frame.check_frame
  (frame_time : Std.U32) (tag_ok : Bool) (now : Std.U32) :
  Result (core.result.Result Unit frame.Reject)
  := do
  if tag_ok
  then
    let b ← frame.is_stale frame_time now
    if b
    then ok (core.result.Result.Err frame.Reject.Stale)
    else
      let b1 ← frame.is_ahead frame_time now
      if b1
      then ok (core.result.Result.Err frame.Reject.Future)
      else ok (core.result.Result.Ok ())
  else ok (core.result.Result.Err frame.Reject.BadTag)

/-- [protocol::lua::is_plain]:
    Source: 'crates/protocol/src/lua.rs', lines 4:0-6:1 -/
def lua.is_plain (b : Std.U8) : Result Bool := do
  if 32#u8 <= b
  then
    if b <= 126#u8
    then if b != 34#u8
         then ok (b != 92#u8)
         else ok false
    else ok false
  else ok false

/-- [protocol::lua::push_escape]:
    Source: 'crates/protocol/src/lua.rs', lines 9:0-14:1 -/
def lua.push_escape
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← alloc.vec.Vec.push out 92#u8
  let i ← b / 100#u8
  let i1 ← 48#u8 + i
  let out2 ← alloc.vec.Vec.push out1 i1
  let i2 ← b / 10#u8
  let i3 ← i2 % 10#u8
  let i4 ← 48#u8 + i3
  let out3 ← alloc.vec.Vec.push out2 i4
  let i5 ← b % 10#u8
  let i6 ← 48#u8 + i5
  alloc.vec.Vec.push out3 i6

/-- [protocol::lua::push_escaped]:
    Source: 'crates/protocol/src/lua.rs', lines 16:0-22:1 -/
def lua.push_escaped
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let b1 ← lua.is_plain b
  if b1
  then alloc.vec.Vec.push out b
  else lua.push_escape out b

/-- [protocol::lua::lua_string]: loop body 0:
    Source: 'crates/protocol/src/lua.rs', lines 30:4-33:5
    Visibility: public -/
@[rust_loop_body]
def lua.lua_string_loop.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let out1 ← lua.push_escaped out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [protocol::lua::lua_string]: loop 0:
    Source: 'crates/protocol/src/lua.rs', lines 30:4-33:5
    Visibility: public -/
@[rust_loop]
def lua.lua_string_loop
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => lua.lua_string_loop.body bytes out1 i1)
    (out, i)

/-- [protocol::lua::lua_string]:
    Source: 'crates/protocol/src/lua.rs', lines 26:0-36:1
    Visibility: public -/
def lua.lua_string (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) 34#u8
  let out1 ← lua.lua_string_loop bytes out 0#usize
  alloc.vec.Vec.push out1 34#u8

/-- [protocol::policy::{impl core::clone::Clone for protocol::policy::Level}::clone]:
    Source: 'crates/protocol/src/policy.rs', lines 4:9-4:14
    Visibility: public -/
def policy.Level.Insts.CoreCloneClone.clone
  (self : policy.Level) : Result policy.Level := do
  ok self

/-- Trait implementation: [protocol::policy::{impl core::clone::Clone for protocol::policy::Level}]
    Source: 'crates/protocol/src/policy.rs', lines 4:9-4:14 -/
@[reducible]
def policy.Level.Insts.CoreCloneClone : core.clone.Clone policy.Level := {
  clone := policy.Level.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [protocol::policy::{impl core::marker::Copy for protocol::policy::Level}]
    Source: 'crates/protocol/src/policy.rs', lines 4:16-4:20 -/
@[reducible]
def policy.Level.Insts.CoreMarkerCopy : core.marker.Copy policy.Level := {
  cloneInst := policy.Level.Insts.CoreCloneClone
}

/-- [protocol::policy::{impl core::clone::Clone for protocol::policy::Answer}::clone]:
    Source: 'crates/protocol/src/policy.rs', lines 12:9-12:14
    Visibility: public -/
def policy.Answer.Insts.CoreCloneClone.clone
  (self : policy.Answer) : Result policy.Answer := do
  ok self

/-- Trait implementation: [protocol::policy::{impl core::clone::Clone for protocol::policy::Answer}]
    Source: 'crates/protocol/src/policy.rs', lines 12:9-12:14 -/
@[reducible]
def policy.Answer.Insts.CoreCloneClone : core.clone.Clone policy.Answer := {
  clone := policy.Answer.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [protocol::policy::{impl core::marker::Copy for protocol::policy::Answer}]
    Source: 'crates/protocol/src/policy.rs', lines 12:16-12:20 -/
@[reducible]
def policy.Answer.Insts.CoreMarkerCopy : core.marker.Copy policy.Answer := {
  cloneInst := policy.Answer.Insts.CoreCloneClone
}

/-- [protocol::policy::rank]:
    Source: 'crates/protocol/src/policy.rs', lines 21:0-27:1 -/
def policy.rank (level : policy.Level) : Result Std.U8 := do
  match level with
  | policy.Level.Ask => ok 0#u8
  | policy.Level.AutoEdit => ok 1#u8
  | policy.Level.FullAuto => ok 2#u8

/-- [protocol::policy::effective_level]:
    Source: 'crates/protocol/src/policy.rs', lines 31:0-37:1
    Visibility: public -/
def policy.effective_level
  (config : policy.Level) (requested : policy.Level) :
  Result policy.Level
  := do
  let i ← policy.rank requested
  let i1 ← policy.rank config
  if i < i1
  then ok requested
  else ok config

/-- [protocol::policy::answer_from_game]:
    Source: 'crates/protocol/src/policy.rs', lines 41:0-46:1
    Visibility: public -/
def policy.answer_from_game
  (answer : policy.Answer) : Result policy.Answer := do
  match answer with
  | policy.Answer.AllowOnce => ok policy.Answer.AllowOnce
  | policy.Answer.AllowAlways => ok policy.Answer.AllowOnce
  | policy.Answer.RejectOnce => ok policy.Answer.RejectOnce
  | policy.Answer.RejectAlways => ok policy.Answer.RejectAlways

/-- [protocol::popup::COMMAND_BUDGET]
    Source: 'crates/protocol/src/popup.rs', lines 6:0-6:38
    Visibility: public -/
@[global_simps, irreducible] def popup.COMMAND_BUDGET : Std.Usize := 300#usize

/-- [protocol::popup::LABEL_BUDGET]
    Source: 'crates/protocol/src/popup.rs', lines 7:0-7:36
    Visibility: public -/
@[global_simps, irreducible] def popup.LABEL_BUDGET : Std.Usize := 120#usize

/-- [protocol::popup::CUT_START]
    Source: 'crates/protocol/src/popup.rs', lines 12:0-12:38 -/
@[global_simps, irreducible]
def popup.CUT_START : Array Std.U8 6#usize :=
  Array.make 6#usize [ 32#u8, 91#u8, 46#u8, 46#u8, 46#u8, 32#u8 ]

/-- [protocol::popup::CUT_END]
    Source: 'crates/protocol/src/popup.rs', lines 13:0-13:47 -/
@[global_simps, irreducible]
def popup.CUT_END : Array Std.U8 16#usize :=
  Array.make 16#usize [
    32#u8, 98#u8, 121#u8, 116#u8, 101#u8, 115#u8, 32#u8, 99#u8, 117#u8, 116#u8,
    32#u8, 46#u8, 46#u8, 46#u8, 93#u8, 32#u8
    ]

/-- [protocol::popup::AGENT_SAYS]
    Source: 'crates/protocol/src/popup.rs', lines 14:0-14:52 -/
@[global_simps, irreducible]
def popup.AGENT_SAYS : Array Std.U8 17#usize :=
  Array.make 17#usize [
    10#u8, 116#u8, 104#u8, 101#u8, 32#u8, 97#u8, 103#u8, 101#u8, 110#u8,
    116#u8, 32#u8, 115#u8, 97#u8, 121#u8, 115#u8, 58#u8, 32#u8
    ]

/-- [protocol::popup::LABEL_CUT]
    Source: 'crates/protocol/src/popup.rs', lines 15:0-15:38 -/
@[global_simps, irreducible]
def popup.LABEL_CUT : Array Std.U8 6#usize :=
  Array.make 6#usize [ 32#u8, 91#u8, 46#u8, 46#u8, 46#u8, 93#u8 ]

/-- [protocol::popup::clamp_to_u32]:
    Source: 'crates/protocol/src/popup.rs', lines 18:0-24:1 -/
def popup.clamp_to_u32 (n : Std.Usize) : Result Std.U32 := do
  let i ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if n > i
  then ok core.num.U32.MAX
  else ok (UScalar.cast .U32 n)

/-- [protocol::popup::hex_digit]:
    Source: 'crates/protocol/src/popup.rs', lines 26:0-28:1 -/
def popup.hex_digit (n : Std.U8) : Result Std.U8 := do
  if n < 10#u8
  then 48#u8 + n
  else let i ← n - 10#u8
       97#u8 + i

/-- [protocol::popup::push_shown]:
    Source: 'crates/protocol/src/popup.rs', lines 30:0-42:1 -/
def popup.push_shown
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  if b = 92#u8
  then let out1 ← alloc.vec.Vec.push out 92#u8
       alloc.vec.Vec.push out1 92#u8
  else
    if 32#u8 <= b
    then
      if b <= 126#u8
      then alloc.vec.Vec.push out b
      else
        let out1 ← alloc.vec.Vec.push out 92#u8
        let out2 ← alloc.vec.Vec.push out1 120#u8
        let i ← b / 16#u8
        let i1 ← popup.hex_digit i
        let out3 ← alloc.vec.Vec.push out2 i1
        let i2 ← b % 16#u8
        let i3 ← popup.hex_digit i2
        alloc.vec.Vec.push out3 i3
    else
      let out1 ← alloc.vec.Vec.push out 92#u8
      let out2 ← alloc.vec.Vec.push out1 120#u8
      let i ← b / 16#u8
      let i1 ← popup.hex_digit i
      let out3 ← alloc.vec.Vec.push out2 i1
      let i2 ← b % 16#u8
      let i3 ← popup.hex_digit i2
      alloc.vec.Vec.push out3 i3

/-- [protocol::popup::push_shown_range]: loop body 0:
    Source: 'crates/protocol/src/popup.rs', lines 46:4-49:5 -/
@[rust_loop_body]
def popup.push_shown_range_loop.body
  (bytes : Slice Std.U8) («end» : Std.Usize) (out : alloc.vec.Vec Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < «end»
  then
    let i1 ← Slice.index_usize bytes i
    let out1 ← popup.push_shown out i1
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [protocol::popup::push_shown_range]: loop 0:
    Source: 'crates/protocol/src/popup.rs', lines 46:4-49:5 -/
@[rust_loop]
def popup.push_shown_range_loop
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) («end» : Std.Usize)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => popup.push_shown_range_loop.body bytes «end» out1 i1)
    (out, i)

/-- [protocol::popup::push_shown_range]:
    Source: 'crates/protocol/src/popup.rs', lines 44:0-50:1 -/
@[reducible]
def popup.push_shown_range
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) (start : Std.Usize)
  («end» : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  popup.push_shown_range_loop out bytes «end» start

/-- [protocol::popup::push_command]:
    Source: 'crates/protocol/src/popup.rs', lines 52:0-64:1 -/
def popup.push_command
  (out : alloc.vec.Vec Std.U8) (command : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let n := Slice.len command
  if n <= popup.COMMAND_BUDGET
  then popup.push_shown_range out command 0#usize n
  else
    let half ← popup.COMMAND_BUDGET / 2#usize
    let out1 ← popup.push_shown_range out command 0#usize half
    let s ← lift (Array.to_slice popup.CUT_START)
    let out2 ← ascii.push_bytes out1 s
    let i ← n - popup.COMMAND_BUDGET
    let i1 ← popup.clamp_to_u32 i
    let out3 ← ascii.push_decimal out2 i1
    let s1 ← lift (Array.to_slice popup.CUT_END)
    let out4 ← ascii.push_bytes out3 s1
    let i2 ← n - half
    popup.push_shown_range out4 command i2 n

/-- [protocol::popup::push_label]:
    Source: 'crates/protocol/src/popup.rs', lines 66:0-74:1 -/
def popup.push_label
  (out : alloc.vec.Vec Std.U8) (label : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let n := Slice.len label
  if n <= popup.LABEL_BUDGET
  then popup.push_shown_range out label 0#usize n
  else
    let out1 ← popup.push_shown_range out label 0#usize popup.LABEL_BUDGET
    let s ← lift (Array.to_slice popup.LABEL_CUT)
    ascii.push_bytes out1 s

/-- [protocol::popup::popup_text]:
    Source: 'crates/protocol/src/popup.rs', lines 79:0-85:1
    Visibility: public -/
def popup.popup_text
  (command : Slice Std.U8) (label : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out ← popup.push_command (alloc.vec.Vec.new Std.U8) command
  let s ← lift (Array.to_slice popup.AGENT_SAYS)
  let out1 ← ascii.push_bytes out s
  popup.push_label out1 label

/-- [protocol::rate::MAX_MESSAGES]
    Source: 'crates/protocol/src/rate.rs', lines 3:0-3:35
    Visibility: public -/
@[global_simps, irreducible] def rate.MAX_MESSAGES : Std.Usize := 10#usize

/-- [protocol::rate::WINDOW_SECONDS]
    Source: 'crates/protocol/src/rate.rs', lines 4:0-4:35
    Visibility: public -/
@[global_simps, irreducible] def rate.WINDOW_SECONDS : Std.U32 := 60#u32

/-- [protocol::rate::MAX_QUEUE]
    Source: 'crates/protocol/src/rate.rs', lines 5:0-5:32
    Visibility: public -/
@[global_simps, irreducible] def rate.MAX_QUEUE : Std.Usize := 20#usize

/-- [protocol::rate::in_window]:
    Source: 'crates/protocol/src/rate.rs', lines 17:0-19:1 -/
def rate.in_window (t : Std.U32) (now : Std.U32) : Result Bool := do
  let i ← lift (UScalar.cast .U64 t)
  let i1 ← lift (UScalar.cast .U64 now)
  if i <= i1
  then
    let i2 ← lift (UScalar.cast .U64 now)
    let i3 ← lift (UScalar.cast .U64 t)
    let i4 ← lift (UScalar.cast .U64 rate.WINDOW_SECONDS)
    let i5 ← i3 + i4
    ok (i2 < i5)
  else ok false

/-- [protocol::rate::still_counting]: loop body 0:
    Source: 'crates/protocol/src/rate.rs', lines 25:4-30:5 -/
@[rust_loop_body]
def rate.still_counting_loop.body
  (times : Slice Std.U32) (now : Std.U32) (kept : alloc.vec.Vec Std.U32)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U32) × Std.Usize) (alloc.vec.Vec
    Std.U32))
  := do
  let i1 := Slice.len times
  if i < i1
  then
    let i2 ← Slice.index_usize times i
    let b ← rate.in_window i2 now
    let kept1 ← if b
                  then alloc.vec.Vec.push kept i2
                  else ok kept
    let i3 ← i + 1#usize
    ok (cont (kept1, i3))
  else ok (done kept)

/-- [protocol::rate::still_counting]: loop 0:
    Source: 'crates/protocol/src/rate.rs', lines 25:4-30:5 -/
@[rust_loop]
def rate.still_counting_loop
  (times : Slice Std.U32) (now : Std.U32) (kept : alloc.vec.Vec Std.U32)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U32)
  := do
  loop
    (fun (kept1, i1) => rate.still_counting_loop.body times now kept1 i1)
    (kept, i)

/-- [protocol::rate::still_counting]:
    Source: 'crates/protocol/src/rate.rs', lines 22:0-32:1 -/
@[reducible]
def rate.still_counting
  (times : Slice Std.U32) (now : Std.U32) :
  Result (alloc.vec.Vec Std.U32)
  := do
  rate.still_counting_loop times now (alloc.vec.Vec.new Std.U32) 0#usize

/-- [protocol::rate::admit_message]:
    Source: 'crates/protocol/src/rate.rs', lines 35:0-43:1
    Visibility: public -/
def rate.admit_message
  (limiter : rate.RateLimiter) (now : Std.U32) :
  Result (Bool × rate.RateLimiter)
  := do
  let s := alloc.vec.Vec.deref limiter.times
  let kept ← rate.still_counting s now
  let i := alloc.vec.Vec.len kept
  if i < rate.MAX_MESSAGES
  then let kept1 ← alloc.vec.Vec.push kept now
       ok (true, { times := kept1 })
  else ok (false, { times := kept })

/-- [protocol::rate::enqueue]:
    Source: 'crates/protocol/src/rate.rs', lines 47:0-54:1
    Visibility: public -/
def rate.enqueue
  (queue : rate.ChatQueue) (id : Std.U32) :
  Result (Option rate.ChatQueue)
  := do
  let i := alloc.vec.Vec.len queue.ids
  if i >= rate.MAX_QUEUE
  then ok none
  else let ids ← alloc.vec.Vec.push queue.ids id
       ok (some { ids })

/-- [protocol::record::RS]
    Source: 'crates/protocol/src/record.rs', lines 9:0-9:24
    Visibility: public -/
@[global_simps, irreducible] def record.RS : Std.U8 := 30#u8

/-- [protocol::record::US]
    Source: 'crates/protocol/src/record.rs', lines 10:0-10:24
    Visibility: public -/
@[global_simps, irreducible] def record.US : Std.U8 := 31#u8

/-- [protocol::record::MAX_ID_LEN]
    Source: 'crates/protocol/src/record.rs', lines 11:0-11:33
    Visibility: public -/
@[global_simps, irreducible] def record.MAX_ID_LEN : Std.Usize := 32#usize

/-- [protocol::record::MAX_RECORDS]
    Source: 'crates/protocol/src/record.rs', lines 12:0-12:34
    Visibility: public -/
@[global_simps, irreducible] def record.MAX_RECORDS : Std.Usize := 16#usize

/-- [protocol::record::is_id_byte]:
    Source: 'crates/protocol/src/record.rs', lines 35:0-37:1 -/
def record.is_id_byte (b : Std.U8) : Result Bool := do
  if 97#u8 <= b
  then
    if b <= 122#u8
    then ok true
    else
      if 48#u8 <= b
      then
        if b <= 57#u8
        then ok true
        else if b = 95#u8
             then ok true
             else ok (b = 45#u8)
      else if b = 95#u8
           then ok true
           else ok (b = 45#u8)
  else
    if 48#u8 <= b
    then
      if b <= 57#u8
      then ok true
      else if b = 95#u8
           then ok true
           else ok (b = 45#u8)
    else if b = 95#u8
         then ok true
         else ok (b = 45#u8)

/-- [protocol::record::is_valid_id]: loop body 0:
    Source: 'crates/protocol/src/record.rs', lines 46:4-53:1
    Visibility: public -/
@[rust_loop_body]
def record.is_valid_id_loop.body
  (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let b ← record.is_id_byte i2
    if b
    then let i3 ← i + 1#usize
         ok (cont i3)
    else ok (done false)
  else ok (done true)

/-- [protocol::record::is_valid_id]: loop 0:
    Source: 'crates/protocol/src/record.rs', lines 46:4-53:1
    Visibility: public -/
@[rust_loop]
def record.is_valid_id_loop
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => record.is_valid_id_loop.body bytes i1)
    i

/-- [protocol::record::is_valid_id]:
    Source: 'crates/protocol/src/record.rs', lines 41:0-53:1
    Visibility: public -/
def record.is_valid_id (bytes : Slice Std.U8) : Result Bool := do
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok false
  else
    let i := Slice.len bytes
    if i > record.MAX_ID_LEN
    then ok false
    else record.is_valid_id_loop bytes 0#usize

/-- [protocol::record::find_byte]: loop body 0:
    Source: 'crates/protocol/src/record.rs', lines 58:4-65:1 -/
@[rust_loop_body]
def record.find_byte_loop.body
  (bytes : Slice Std.U8) («end» : Std.Usize) (target : Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if i < «end»
  then
    let i1 ← Slice.index_usize bytes i
    if i1 = target
    then ok (done i)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done «end»)

/-- [protocol::record::find_byte]: loop 0:
    Source: 'crates/protocol/src/record.rs', lines 58:4-65:1 -/
@[rust_loop]
def record.find_byte_loop
  (bytes : Slice Std.U8) («end» : Std.Usize) (target : Std.U8)
  (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun i1 => record.find_byte_loop.body bytes «end» target i1)
    i

/-- [protocol::record::find_byte]:
    Source: 'crates/protocol/src/record.rs', lines 56:0-65:1 -/
@[reducible]
def record.find_byte
  (bytes : Slice Std.U8) («from» : Std.Usize) («end» : Std.Usize)
  (target : Std.U8) :
  Result Std.Usize
  := do
  record.find_byte_loop bytes «end» target «from»

/-- [protocol::record::copy_field]:
    Source: 'crates/protocol/src/record.rs', lines 67:0-71:1 -/
def record.copy_field
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  ascii.push_range (alloc.vec.Vec.new Std.U8) bytes start «end»

/-- [protocol::record::digits_value]: loop body 0:
    Source: 'crates/protocol/src/record.rs', lines 77:4-86:1 -/
@[rust_loop_body]
def record.digits_value_loop.body
  (bytes : Slice Std.U8) («end» : Std.Usize) (value : Std.U64)
  (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.Usize) (Option Std.U64))
  := do
  if i < «end»
  then
    let b ← Slice.index_usize bytes i
    if b < 48#u8
    then ok (done none)
    else
      if b > 57#u8
      then ok (done none)
      else
        let i1 ← value * 10#u64
        let i2 ← b - 48#u8
        let i3 ← lift (UScalar.cast .U64 i2)
        let value1 ← i1 + i3
        let i4 ← i + 1#usize
        ok (cont (value1, i4))
  else ok (done (some value))

/-- [protocol::record::digits_value]: loop 0:
    Source: 'crates/protocol/src/record.rs', lines 77:4-86:1 -/
@[rust_loop]
def record.digits_value_loop
  (bytes : Slice Std.U8) («end» : Std.Usize) (value : Std.U64)
  (i : Std.Usize) :
  Result (Option Std.U64)
  := do
  loop
    (fun (value1, i1) => record.digits_value_loop.body bytes «end» value1 i1)
    (value, i)

/-- [protocol::record::digits_value]:
    Source: 'crates/protocol/src/record.rs', lines 74:0-86:1 -/
@[reducible]
def record.digits_value
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (Option Std.U64)
  := do
  record.digits_value_loop bytes «end» 0#u64 start

/-- [protocol::record::parse_decimal]:
    Source: 'crates/protocol/src/record.rs', lines 90:0-105:1 -/
def record.parse_decimal
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (Option Std.U32)
  := do
  let n ← «end» - start
  if n = 0#usize
  then ok none
  else
    if n > 10#usize
    then ok none
    else
      if n > 1#usize
      then
        let i ← Slice.index_usize bytes start
        if i = 48#u8
        then ok none
        else
          let o ← record.digits_value bytes start «end»
          match o with
          | none => ok none
          | some value =>
            let i1 ← lift (UScalar.cast .U64 core.num.U32.MAX)
            if value > i1
            then ok none
            else let i2 ← lift (UScalar.cast .U32 value)
                 ok (some i2)
      else
        let o ← record.digits_value bytes start «end»
        match o with
        | none => ok none
        | some value =>
          let i ← lift (UScalar.cast .U64 core.num.U32.MAX)
          if value > i
          then ok none
          else let i1 ← lift (UScalar.cast .U32 value)
               ok (some i1)

/-- [protocol::record::parse_record]:
    Source: 'crates/protocol/src/record.rs', lines 108:0-153:1 -/
def record.parse_record
  (bytes : Slice Std.U8) (start : Std.Usize) («end» : Std.Usize) :
  Result (core.result.Result record.Record record.RecordError)
  := do
  let u1 ← record.find_byte bytes start «end» record.US
  if u1 = «end»
  then ok (core.result.Result.Err record.RecordError.MissingField)
  else
    let i ← u1 + 1#usize
    let u2 ← record.find_byte bytes i «end» record.US
    if u2 = «end»
    then ok (core.result.Result.Err record.RecordError.MissingField)
    else
      let i1 ← u2 + 1#usize
      let u3 ← record.find_byte bytes i1 «end» record.US
      if u3 = «end»
      then ok (core.result.Result.Err record.RecordError.MissingField)
      else
        let i2 ← u3 + 1#usize
        let u4 ← record.find_byte bytes i2 «end» record.US
        if u4 = «end»
        then ok (core.result.Result.Err record.RecordError.MissingField)
        else
          let i3 ← u4 + 1#usize
          let u5 ← record.find_byte bytes i3 «end» record.US
          if u5 = «end»
          then ok (core.result.Result.Err record.RecordError.MissingField)
          else
            let i4 ← u5 + 1#usize
            let u6 ← record.find_byte bytes i4 «end» record.US
            if u6 = «end»
            then ok (core.result.Result.Err record.RecordError.MissingField)
            else
              let token ← record.copy_field bytes start u1
              let s := alloc.vec.Vec.deref token
              let b ← record.is_valid_id s
              if b
              then
                let chat ← record.copy_field bytes i u2
                let s1 := alloc.vec.Vec.deref chat
                let b1 ← record.is_valid_id s1
                if b1
                then
                  let o ← record.parse_decimal bytes i1 u3
                  match o with
                  | none =>
                    ok (core.result.Result.Err record.RecordError.BadId)
                  | some id =>
                    let v ← record.copy_field bytes i2 u4
                    let v1 ← record.copy_field bytes i3 u5
                    let v2 ← record.copy_field bytes i4 u6
                    let i5 ← u6 + 1#usize
                    let v3 ← record.copy_field bytes i5 «end»
                    ok (core.result.Result.Ok
                      {
                        token,
                        chat,
                        id,
                        cwd := v,
                        flags := v1,
                        «name» := v2,
                        text := v3
                      })
                else ok (core.result.Result.Err record.RecordError.BadChat)
              else ok (core.result.Result.Err record.RecordError.BadToken)

/-- [protocol::record::parse_records]: loop body 0:
    Source: 'crates/protocol/src/record.rs', lines 168:4-184:1
    Visibility: public -/
@[rust_loop_body]
def record.parse_records_loop.body
  (payload : Slice Std.U8) (records : alloc.vec.Vec record.Record)
  (start : Std.Usize) (more : Bool) :
  Result (ControlFlow ((alloc.vec.Vec record.Record) × Std.Usize × Bool)
    (core.result.Result (alloc.vec.Vec record.Record) record.RecordError))
  := do
  if more
  then
    let i := Slice.len payload
    let «end» ← record.find_byte payload start i record.RS
    let i1 := alloc.vec.Vec.len records
    if i1 = record.MAX_RECORDS
    then ok (done (core.result.Result.Err record.RecordError.TooMany))
    else
      let r ← record.parse_record payload start «end»
      match r with
      | core.result.Result.Ok r1 =>
        let records1 ← alloc.vec.Vec.push records r1
        let i2 := Slice.len payload
        if «end» = i2
        then ok (cont (records1, start, false))
        else
          let start1 ← «end» + 1#usize
          ok (cont (records1, start1, true))
      | core.result.Result.Err e => ok (done (core.result.Result.Err e))
  else ok (done (core.result.Result.Ok records))

/-- [protocol::record::parse_records]: loop 0:
    Source: 'crates/protocol/src/record.rs', lines 168:4-184:1
    Visibility: public -/
@[rust_loop]
def record.parse_records_loop
  (payload : Slice Std.U8) (records : alloc.vec.Vec record.Record)
  (start : Std.Usize) (more : Bool) :
  Result (core.result.Result (alloc.vec.Vec record.Record) record.RecordError)
  := do
  loop
    (fun (records1, start1, more1) => record.parse_records_loop.body payload
      records1 start1 more1)
    (records, start, more)

/-- [protocol::record::parse_records]:
    Source: 'crates/protocol/src/record.rs', lines 159:0-184:1
    Visibility: public -/
def record.parse_records
  (payload : Slice Std.U8) :
  Result (core.result.Result (alloc.vec.Vec record.Record) record.RecordError)
  := do
  let b ← core.slice.Slice.is_empty payload
  if b
  then ok (core.result.Result.Err record.RecordError.Empty)
  else
    record.parse_records_loop payload (alloc.vec.Vec.new record.Record) 0#usize
      true

/-- [protocol::record::push_record]:
    Source: 'crates/protocol/src/record.rs', lines 186:0-200:1 -/
def record.push_record
  (out : alloc.vec.Vec Std.U8) (r : record.Record) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let s := alloc.vec.Vec.deref r.token
  let out1 ← ascii.push_bytes out s
  let out2 ← alloc.vec.Vec.push out1 record.US
  let s1 := alloc.vec.Vec.deref r.chat
  let out3 ← ascii.push_bytes out2 s1
  let out4 ← alloc.vec.Vec.push out3 record.US
  let out5 ← ascii.push_decimal out4 r.id
  let out6 ← alloc.vec.Vec.push out5 record.US
  let s2 := alloc.vec.Vec.deref r.cwd
  let out7 ← ascii.push_bytes out6 s2
  let out8 ← alloc.vec.Vec.push out7 record.US
  let s3 := alloc.vec.Vec.deref r.flags
  let out9 ← ascii.push_bytes out8 s3
  let out10 ← alloc.vec.Vec.push out9 record.US
  let s4 := alloc.vec.Vec.deref r.name
  let out11 ← ascii.push_bytes out10 s4
  let out12 ← alloc.vec.Vec.push out11 record.US
  let s5 := alloc.vec.Vec.deref r.text
  ascii.push_bytes out12 s5

/-- [protocol::record::push_separator]:
    Source: 'crates/protocol/src/record.rs', lines 203:0-207:1 -/
def record.push_separator
  (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  if i > 0#usize
  then alloc.vec.Vec.push out record.RS
  else ok out

/-- [protocol::record::serialize_records]: loop body 0:
    Source: 'crates/protocol/src/record.rs', lines 213:4-217:5
    Visibility: public -/
@[rust_loop_body]
def record.serialize_records_loop.body
  (records : Slice record.Record) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len records
  if i < i1
  then
    let out1 ← record.push_separator out i
    let r ← Slice.index_usize records i
    let out2 ← record.push_record out1 r
    let i2 ← i + 1#usize
    ok (cont (out2, i2))
  else ok (done out)

/-- [protocol::record::serialize_records]: loop 0:
    Source: 'crates/protocol/src/record.rs', lines 213:4-217:5
    Visibility: public -/
@[rust_loop]
def record.serialize_records_loop
  (records : Slice record.Record) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => record.serialize_records_loop.body records out1 i1)
    (out, i)

/-- [protocol::record::serialize_records]:
    Source: 'crates/protocol/src/record.rs', lines 210:0-219:1
    Visibility: public -/
@[reducible]
def record.serialize_records
  (records : Slice record.Record) : Result (alloc.vec.Vec Std.U8) := do
  record.serialize_records_loop records (alloc.vec.Vec.new Std.U8) 0#usize

/-- [protocol::seen::SEEN_CAPACITY]
    Source: 'crates/protocol/src/seen.rs', lines 5:0-5:38
    Visibility: public -/
@[global_simps, irreducible] def seen.SEEN_CAPACITY : Std.Usize := 1000#usize

/-- [protocol::seen::new_seen]:
    Source: 'crates/protocol/src/seen.rs', lines 18:0-22:1
    Visibility: public -/
def seen.new_seen : Result seen.Seen := do
  ok { entries := (alloc.vec.Vec.new seen.Entry) }

/-- [protocol::seen::contains]: loop body 0:
    Source: 'crates/protocol/src/seen.rs', lines 40:4-47:1 -/
@[rust_loop_body]
def seen.contains_loop.body
  (entries : Slice seen.Entry) (token : Slice Std.U8) (id : Std.U32)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len entries
  if i < i1
  then
    let e ← Slice.index_usize entries i
    if e.id = id
    then
      let s := alloc.vec.Vec.deref e.token
      let b ← seen.bytes_equal s token
      if b
      then ok (done true)
      else let i2 ← i + 1#usize
           ok (cont i2)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done false)

/-- [protocol::seen::contains]: loop 0:
    Source: 'crates/protocol/src/seen.rs', lines 40:4-47:1 -/
@[rust_loop]
def seen.contains_loop
  (entries : Slice seen.Entry) (token : Slice Std.U8) (id : Std.U32)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => seen.contains_loop.body entries token id i1)
    i

/-- [protocol::seen::contains]:
    Source: 'crates/protocol/src/seen.rs', lines 38:0-47:1 -/
@[reducible]
def seen.contains
  (entries : Slice seen.Entry) (token : Slice Std.U8) (id : Std.U32) :
  Result Bool
  := do
  seen.contains_loop entries token id 0#usize

/-- [protocol::seen::copy_entries]: loop body 0:
    Source: 'crates/protocol/src/seen.rs', lines 59:4-65:5 -/
@[rust_loop_body]
def seen.copy_entries_loop.body
  (entries : Slice seen.Entry) (out : alloc.vec.Vec seen.Entry) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec seen.Entry) × Std.Usize) (alloc.vec.Vec
    seen.Entry))
  := do
  let i1 := Slice.len entries
  if i < i1
  then
    let e ← Slice.index_usize entries i
    let s := alloc.vec.Vec.deref e.token
    let v ← seen.copy_bytes s
    let out1 ← alloc.vec.Vec.push out { e with token := v }
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [protocol::seen::copy_entries]: loop 0:
    Source: 'crates/protocol/src/seen.rs', lines 59:4-65:5 -/
@[rust_loop]
def seen.copy_entries_loop
  (entries : Slice seen.Entry) (out : alloc.vec.Vec seen.Entry) (i : Std.Usize)
  :
  Result (alloc.vec.Vec seen.Entry)
  := do
  loop
    (fun (out1, i1) => seen.copy_entries_loop.body entries out1 i1)
    (out, i)

/-- [protocol::seen::copy_entries]:
    Source: 'crates/protocol/src/seen.rs', lines 56:0-67:1 -/
@[reducible]
def seen.copy_entries
  (entries : Slice seen.Entry) («from» : Std.Usize) :
  Result (alloc.vec.Vec seen.Entry)
  := do
  seen.copy_entries_loop entries (alloc.vec.Vec.new seen.Entry) «from»

/-- [protocol::seen::first_kept]:
    Source: 'crates/protocol/src/seen.rs', lines 70:0-72:1 -/
def seen.first_kept (len : Std.Usize) : Result Std.Usize := do
  if len >= seen.SEEN_CAPACITY
  then ok 1#usize
  else ok 0#usize

/-- [protocol::seen::admit]:
    Source: 'crates/protocol/src/seen.rs', lines 76:0-86:1
    Visibility: public -/
def seen.admit
  (history : seen.Seen) (token : Slice Std.U8) (id : Std.U32) :
  Result (Bool × seen.Seen)
  := do
  let s := alloc.vec.Vec.deref history.entries
  let b ← seen.contains s token id
  if b
  then ok (false, history)
  else
    let s1 := alloc.vec.Vec.deref history.entries
    let i := alloc.vec.Vec.len history.entries
    let i1 ← seen.first_kept i
    let entries ← seen.copy_entries s1 i1
    let v ← seen.copy_bytes token
    let entries1 ←
      alloc.vec.Vec.push entries ({ token := v, id } : seen.Entry)
    ok (true, { entries := entries1 })

/-- [protocol::slot::SLOTS]
    Source: 'crates/protocol/src/slot.rs', lines 8:0-8:30
    Visibility: public -/
@[global_simps, irreducible] def slot.SLOTS : Std.Usize := 1000#usize

/-- [protocol::slot::SLOT_WINDOW]
    Source: 'crates/protocol/src/slot.rs', lines 10:0-10:34
    Visibility: public -/
@[global_simps, irreducible] def slot.SLOT_WINDOW : Std.Usize := 30#usize

/-- [protocol::slot::MAX_REPLIES]
    Source: 'crates/protocol/src/slot.rs', lines 11:0-11:34
    Visibility: public -/
@[global_simps, irreducible] def slot.MAX_REPLIES : Std.Usize := 30#usize

/-- [protocol::slot::MAX_TEXT]
    Source: 'crates/protocol/src/slot.rs', lines 12:0-12:35
    Visibility: public -/
@[global_simps, irreducible] def slot.MAX_TEXT : Std.Usize := 32768#usize

/-- [protocol::slot::SLOT_BODY_LIMIT]
    Source: 'crates/protocol/src/slot.rs', lines 13:0-13:47
    Visibility: public -/
@[global_simps, irreducible]
def slot.SLOT_BODY_LIMIT : Result Std.Usize := 1024#usize * 1024#usize

/-- [protocol::slot::{impl core::clone::Clone for protocol::slot::Status}::clone]:
    Source: 'crates/protocol/src/slot.rs', lines 15:9-15:14
    Visibility: public -/
def slot.Status.Insts.CoreCloneClone.clone
  (self : slot.Status) : Result slot.Status := do
  ok self

/-- Trait implementation: [protocol::slot::{impl core::clone::Clone for protocol::slot::Status}]
    Source: 'crates/protocol/src/slot.rs', lines 15:9-15:14 -/
@[reducible]
def slot.Status.Insts.CoreCloneClone : core.clone.Clone slot.Status := {
  clone := slot.Status.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [protocol::slot::{impl core::marker::Copy for protocol::slot::Status}]
    Source: 'crates/protocol/src/slot.rs', lines 15:16-15:20 -/
@[reducible]
def slot.Status.Insts.CoreMarkerCopy : core.marker.Copy slot.Status := {
  cloneInst := slot.Status.Insts.CoreCloneClone
}

/-- [protocol::slot::HEAD]
    Source: 'crates/protocol/src/slot.rs', lines 29:0-29:70 -/
@[global_simps, irreducible]
def slot.HEAD : Array Std.U8 42#usize :=
  Array.make 42#usize [
    71#u8, 110#u8, 111#u8, 109#u8, 105#u8, 115#u8, 104#u8, 82#u8, 101#u8,
    108#u8, 97#u8, 121#u8, 95#u8, 83#u8, 108#u8, 111#u8, 116#u8, 68#u8, 97#u8,
    116#u8, 97#u8, 32#u8, 61#u8, 32#u8, 123#u8, 112#u8, 114#u8, 111#u8, 116#u8,
    111#u8, 32#u8, 61#u8, 32#u8, 49#u8, 44#u8, 32#u8, 110#u8, 111#u8, 119#u8,
    32#u8, 61#u8, 32#u8
    ]

/-- [protocol::slot::REPLIES]
    Source: 'crates/protocol/src/slot.rs', lines 30:0-30:46 -/
@[global_simps, irreducible]
def slot.REPLIES : Array Std.U8 14#usize :=
  Array.make 14#usize [
    44#u8, 32#u8, 114#u8, 101#u8, 112#u8, 108#u8, 105#u8, 101#u8, 115#u8,
    32#u8, 61#u8, 32#u8, 123#u8, 10#u8
    ]

/-- [protocol::slot::TAIL]
    Source: 'crates/protocol/src/slot.rs', lines 31:0-31:31 -/
@[global_simps, irreducible]
def slot.TAIL : Array Std.U8 3#usize :=
  Array.make 3#usize [ 125#u8, 125#u8, 10#u8 ]

/-- [protocol::slot::CHAT]
    Source: 'crates/protocol/src/slot.rs', lines 32:0-32:35 -/
@[global_simps, irreducible]
def slot.CHAT : Array Std.U8 8#usize :=
  Array.make 8#usize [
    123#u8, 99#u8, 104#u8, 97#u8, 116#u8, 32#u8, 61#u8, 32#u8
    ]

/-- [protocol::slot::ID]
    Source: 'crates/protocol/src/slot.rs', lines 33:0-33:32 -/
@[global_simps, irreducible]
def slot.ID : Array Std.U8 7#usize :=
  Array.make 7#usize [ 44#u8, 32#u8, 105#u8, 100#u8, 32#u8, 61#u8, 32#u8 ]

/-- [protocol::slot::STATUS]
    Source: 'crates/protocol/src/slot.rs', lines 34:0-34:41 -/
@[global_simps, irreducible]
def slot.STATUS : Array Std.U8 11#usize :=
  Array.make 11#usize [
    44#u8, 32#u8, 115#u8, 116#u8, 97#u8, 116#u8, 117#u8, 115#u8, 32#u8, 61#u8,
    32#u8
    ]

/-- [protocol::slot::TEXT]
    Source: 'crates/protocol/src/slot.rs', lines 35:0-35:36 -/
@[global_simps, irreducible]
def slot.TEXT : Array Std.U8 9#usize :=
  Array.make 9#usize [
    44#u8, 32#u8, 116#u8, 101#u8, 120#u8, 116#u8, 32#u8, 61#u8, 32#u8
    ]

/-- [protocol::slot::REPLY_END]
    Source: 'crates/protocol/src/slot.rs', lines 36:0-36:36 -/
@[global_simps, irreducible]
def slot.REPLY_END : Array Std.U8 3#usize :=
  Array.make 3#usize [ 125#u8, 44#u8, 10#u8 ]

/-- [protocol::slot::WORKING]
    Source: 'crates/protocol/src/slot.rs', lines 37:0-37:41 -/
@[global_simps, irreducible]
def slot.WORKING : Array Std.U8 9#usize :=
  Array.make 9#usize [
    34#u8, 119#u8, 111#u8, 114#u8, 107#u8, 105#u8, 110#u8, 103#u8, 34#u8
    ]

/-- [protocol::slot::DONE]
    Source: 'crates/protocol/src/slot.rs', lines 38:0-38:35 -/
@[global_simps, irreducible]
def slot.DONE : Array Std.U8 6#usize :=
  Array.make 6#usize [ 34#u8, 100#u8, 111#u8, 110#u8, 101#u8, 34#u8 ]

/-- [protocol::slot::ERROR]
    Source: 'crates/protocol/src/slot.rs', lines 39:0-39:37 -/
@[global_simps, irreducible]
def slot.ERROR : Array Std.U8 7#usize :=
  Array.make 7#usize [ 34#u8, 101#u8, 114#u8, 114#u8, 111#u8, 114#u8, 34#u8 ]

/-- [protocol::slot::escaped_len]:
    Source: 'crates/protocol/src/slot.rs', lines 42:0-44:1 -/
def slot.escaped_len (b : Std.U8) : Result Std.Usize := do
  let b1 ← lua.is_plain b
  if b1
  then ok 1#usize
  else ok 4#usize

/-- [protocol::slot::next_fits]:
    Source: 'crates/protocol/src/slot.rs', lines 46:0-48:1 -/
def slot.next_fits
  (text : Slice Std.U8) (i : Std.Usize) (size : Std.Usize) : Result Bool := do
  let i1 := Slice.len text
  if i < i1
  then
    let i2 ← Slice.index_usize text i
    let i3 ← slot.escaped_len i2
    let i4 ← size + i3
    ok (i4 <= slot.MAX_TEXT)
  else ok false

/-- [protocol::slot::fitting_prefix]: loop body 0:
    Source: 'crates/protocol/src/slot.rs', lines 54:4-57:5 -/
@[rust_loop_body]
def slot.fitting_prefix_loop.body
  (text : Slice Std.U8) (size : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  let b ← slot.next_fits text i size
  if b
  then
    let i1 ← Slice.index_usize text i
    let i2 ← slot.escaped_len i1
    let size1 ← size + i2
    let i3 ← i + 1#usize
    ok (cont (size1, i3))
  else ok (done i)

/-- [protocol::slot::fitting_prefix]: loop 0:
    Source: 'crates/protocol/src/slot.rs', lines 54:4-57:5 -/
@[rust_loop]
def slot.fitting_prefix_loop
  (text : Slice Std.U8) (size : Std.Usize) (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (size1, i1) => slot.fitting_prefix_loop.body text size1 i1)
    (size, i)

/-- [protocol::slot::fitting_prefix]:
    Source: 'crates/protocol/src/slot.rs', lines 51:0-59:1 -/
@[reducible]
def slot.fitting_prefix (text : Slice Std.U8) : Result Std.Usize := do
  slot.fitting_prefix_loop text 2#usize 0#usize

/-- [protocol::slot::min_len]:
    Source: 'crates/protocol/src/slot.rs', lines 61:0-63:1 -/
def slot.min_len (n : Std.Usize) (max : Std.Usize) : Result Std.Usize := do
  if n > max
  then ok max
  else ok n

/-- [protocol::slot::first_kept]:
    Source: 'crates/protocol/src/slot.rs', lines 66:0-72:1 -/
def slot.first_kept (len : Std.Usize) : Result Std.Usize := do
  if len > slot.MAX_REPLIES
  then len - slot.MAX_REPLIES
  else ok 0#usize

/-- [protocol::slot::prepare_reply]:
    Source: 'crates/protocol/src/slot.rs', lines 74:0-90:1 -/
def slot.prepare_reply (reply : slot.Reply) : Result slot.Reply := do
  let s := alloc.vec.Vec.deref reply.chat
  let i := alloc.vec.Vec.len reply.chat
  let i1 ← slot.min_len i record.MAX_ID_LEN
  let chat ← ascii.push_range (alloc.vec.Vec.new Std.U8) s 0#usize i1
  let s1 := alloc.vec.Vec.deref reply.text
  let s2 := alloc.vec.Vec.deref reply.text
  let i2 ← slot.fitting_prefix s2
  let text ← ascii.push_range (alloc.vec.Vec.new Std.U8) s1 0#usize i2
  ok { reply with chat, text }

/-- [protocol::slot::prepare_replies]: loop body 0:
    Source: 'crates/protocol/src/slot.rs', lines 98:4-101:5
    Visibility: public -/
@[rust_loop_body]
def slot.prepare_replies_loop.body
  (replies : Slice slot.Reply) (out : alloc.vec.Vec slot.Reply) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec slot.Reply) × Std.Usize) (alloc.vec.Vec
    slot.Reply))
  := do
  let i1 := Slice.len replies
  if i < i1
  then
    let r ← Slice.index_usize replies i
    let r1 ← slot.prepare_reply r
    let out1 ← alloc.vec.Vec.push out r1
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [protocol::slot::prepare_replies]: loop 0:
    Source: 'crates/protocol/src/slot.rs', lines 98:4-101:5
    Visibility: public -/
@[rust_loop]
def slot.prepare_replies_loop
  (replies : Slice slot.Reply) (out : alloc.vec.Vec slot.Reply) (i : Std.Usize)
  :
  Result (alloc.vec.Vec slot.Reply)
  := do
  loop
    (fun (out1, i1) => slot.prepare_replies_loop.body replies out1 i1)
    (out, i)

/-- [protocol::slot::prepare_replies]:
    Source: 'crates/protocol/src/slot.rs', lines 95:0-103:1
    Visibility: public -/
def slot.prepare_replies
  (replies : Slice slot.Reply) : Result (alloc.vec.Vec slot.Reply) := do
  let i := Slice.len replies
  let i1 ← slot.first_kept i
  slot.prepare_replies_loop replies (alloc.vec.Vec.new slot.Reply) i1

/-- [protocol::slot::push_status]:
    Source: 'crates/protocol/src/slot.rs', lines 105:0-111:1 -/
def slot.push_status
  (out : alloc.vec.Vec Std.U8) (status : slot.Status) :
  Result (alloc.vec.Vec Std.U8)
  := do
  match status with
  | slot.Status.Working =>
    let s ← lift (Array.to_slice slot.WORKING)
    ascii.push_bytes out s
  | slot.Status.Done =>
    let s ← lift (Array.to_slice slot.DONE)
    ascii.push_bytes out s
  | slot.Status.Error =>
    let s ← lift (Array.to_slice slot.ERROR)
    ascii.push_bytes out s

/-- [protocol::slot::push_reply]:
    Source: 'crates/protocol/src/slot.rs', lines 113:0-123:1 -/
def slot.push_reply
  (out : alloc.vec.Vec Std.U8) (reply : slot.Reply) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let s ← lift (Array.to_slice slot.CHAT)
  let out1 ← ascii.push_bytes out s
  let s1 := alloc.vec.Vec.deref reply.chat
  let v ← lua.lua_string s1
  let s2 := alloc.vec.Vec.deref v
  let out2 ← ascii.push_bytes out1 s2
  let s3 ← lift (Array.to_slice slot.ID)
  let out3 ← ascii.push_bytes out2 s3
  let out4 ← ascii.push_decimal out3 reply.id
  let s4 ← lift (Array.to_slice slot.STATUS)
  let out5 ← ascii.push_bytes out4 s4
  let out6 ← slot.push_status out5 reply.status
  let s5 ← lift (Array.to_slice slot.TEXT)
  let out7 ← ascii.push_bytes out6 s5
  let s6 := alloc.vec.Vec.deref reply.text
  let v1 ← lua.lua_string s6
  let s7 := alloc.vec.Vec.deref v1
  let out8 ← ascii.push_bytes out7 s7
  let s8 ← lift (Array.to_slice slot.REPLY_END)
  ascii.push_bytes out8 s8

/-- [protocol::slot::slot_body]: loop body 0:
    Source: 'crates/protocol/src/slot.rs', lines 134:4-137:5
    Visibility: public -/
@[rust_loop_body]
def slot.slot_body_loop.body
  (replies : Slice slot.Reply) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len replies
  if i < i1
  then
    let r ← Slice.index_usize replies i
    let out1 ← slot.push_reply out r
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [protocol::slot::slot_body]: loop 0:
    Source: 'crates/protocol/src/slot.rs', lines 134:4-137:5
    Visibility: public -/
@[rust_loop]
def slot.slot_body_loop
  (replies : Slice slot.Reply) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => slot.slot_body_loop.body replies out1 i1)
    (out, i)

/-- [protocol::slot::slot_body]:
    Source: 'crates/protocol/src/slot.rs', lines 128:0-140:1
    Visibility: public -/
def slot.slot_body
  (now : Std.U32) (replies : Slice slot.Reply) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let s ← lift (Array.to_slice slot.HEAD)
  let out ← ascii.push_bytes (alloc.vec.Vec.new Std.U8) s
  let out1 ← ascii.push_decimal out now
  let s1 ← lift (Array.to_slice slot.REPLIES)
  let out2 ← ascii.push_bytes out1 s1
  let out3 ← slot.slot_body_loop replies out2 0#usize
  let s2 ← lift (Array.to_slice slot.TAIL)
  ascii.push_bytes out3 s2

/-- [protocol::wow_text::push_safe]:
    Source: 'crates/protocol/src/wow_text.rs', lines 4:0-9:1 -/
def wow_text.push_safe
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← if b = 124#u8
               then alloc.vec.Vec.push out 124#u8
               else ok out
  alloc.vec.Vec.push out1 b

/-- [protocol::wow_text::chat_safe]: loop body 0:
    Source: 'crates/protocol/src/wow_text.rs', lines 16:4-19:5
    Visibility: public -/
@[rust_loop_body]
def wow_text.chat_safe_loop.body
  (text : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len text
  if i < i1
  then
    let i2 ← Slice.index_usize text i
    let out1 ← wow_text.push_safe out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [protocol::wow_text::chat_safe]: loop 0:
    Source: 'crates/protocol/src/wow_text.rs', lines 16:4-19:5
    Visibility: public -/
@[rust_loop]
def wow_text.chat_safe_loop
  (text : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => wow_text.chat_safe_loop.body text out1 i1)
    (out, i)

/-- [protocol::wow_text::chat_safe]:
    Source: 'crates/protocol/src/wow_text.rs', lines 13:0-21:1
    Visibility: public -/
@[reducible]
def wow_text.chat_safe
  (text : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  wow_text.chat_safe_loop text (alloc.vec.Vec.new Std.U8) 0#usize

end protocol
