-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [protocol]: function definitions
import Aeneas
import Protocol.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace protocol

/-- [protocol::cell::BYTES_PER_GROUP]
    Source: 'crates/protocol/src/cell.rs', lines 11:0-11:37
    Visibility: public -/
@[global_simps, irreducible] def cell.BYTES_PER_GROUP : Std.Usize := 3#usize

/-- [protocol::cell::CELLS_PER_GROUP]
    Source: 'crates/protocol/src/cell.rs', lines 12:0-12:37
    Visibility: public -/
@[global_simps, irreducible] def cell.CELLS_PER_GROUP : Std.Usize := 8#usize

/-- [protocol::cell::group_bits]:
    Source: 'crates/protocol/src/cell.rs', lines 14:0-16:1 -/
def cell.group_bits
  (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result Std.U32 := do
  let i ← lift (UScalar.cast .U32 a)
  let i1 ← i <<< 16#i32
  let i2 ← lift (UScalar.cast .U32 b)
  let i3 ← i2 <<< 8#i32
  let i4 ← lift (i1 ||| i3)
  let i5 ← lift (UScalar.cast .U32 c)
  ok (i4 ||| i5)

/-- [protocol::cell::cell_at]:
    Source: 'crates/protocol/src/cell.rs', lines 18:0-20:1 -/
def cell.cell_at (bits : Std.U32) (shift : Std.U32) : Result Std.U8 := do
  let i ← bits >>> shift
  let i1 ← lift (i &&& 7#u32)
  ok (UScalar.cast .U8 i1)

/-- [protocol::cell::append_cell]:
    Source: 'crates/protocol/src/cell.rs', lines 22:0-24:1 -/
def cell.append_cell (bits : Std.U32) (cell : Std.U8) : Result Std.U32 := do
  let i ← bits <<< 3#i32
  let i1 ← lift (UScalar.cast .U32 cell)
  ok (i ||| i1)

/-- [protocol::cell::byte_at]:
    Source: 'crates/protocol/src/cell.rs', lines 26:0-28:1 -/
def cell.byte_at (bits : Std.U32) (shift : Std.U32) : Result Std.U8 := do
  let i ← bits >>> shift
  ok (UScalar.cast .U8 i)

/-- [protocol::cell::encode_group]:
    Source: 'crates/protocol/src/cell.rs', lines 32:0-44:1
    Visibility: public -/
def cell.encode_group
  (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result (Array Std.U8 8#usize) := do
  let bits ← cell.group_bits a b c
  let i ← cell.cell_at bits 21#u32
  let i1 ← cell.cell_at bits 18#u32
  let i2 ← cell.cell_at bits 15#u32
  let i3 ← cell.cell_at bits 12#u32
  let i4 ← cell.cell_at bits 9#u32
  let i5 ← cell.cell_at bits 6#u32
  let i6 ← cell.cell_at bits 3#u32
  let i7 ← cell.cell_at bits 0#u32
  ok (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ])

/-- [protocol::cell::decode_group]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 52:4-60:1
    Visibility: public -/
@[rust_loop_body]
def cell.decode_group_loop.body
  (cells : Array Std.U8 8#usize) (bits : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (Option (Array Std.U8 3#usize)))
  := do
  if i < cell.CELLS_PER_GROUP
  then
    let i1 ← Array.index_usize cells i
    if i1 > 7#u8
    then ok (done none)
    else
      let bits1 ← cell.append_cell bits i1
      let i2 ← i + 1#usize
      ok (cont (bits1, i2))
  else
    let i1 ← cell.byte_at bits 16#u32
    let i2 ← cell.byte_at bits 8#u32
    let i3 ← cell.byte_at bits 0#u32
    ok (done (some (Array.make 3#usize [ i1, i2, i3 ])))

/-- [protocol::cell::decode_group]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 52:4-60:1
    Visibility: public -/
@[rust_loop]
def cell.decode_group_loop
  (cells : Array Std.U8 8#usize) (bits : Std.U32) (i : Std.Usize) :
  Result (Option (Array Std.U8 3#usize))
  := do
  loop
    (fun (bits1, i1) => cell.decode_group_loop.body cells bits1 i1)
    (bits, i)

/-- [protocol::cell::decode_group]:
    Source: 'crates/protocol/src/cell.rs', lines 49:0-60:1
    Visibility: public -/
@[reducible]
def cell.decode_group
  (cells : Array Std.U8 8#usize) : Result (Option (Array Std.U8 3#usize)) := do
  cell.decode_group_loop cells 0#u32 0#usize

/-- [protocol::cell::byte_or_zero]:
    Source: 'crates/protocol/src/cell.rs', lines 62:0-64:1 -/
def cell.byte_or_zero
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Std.U8 := do
  let i1 := Slice.len bytes
  if i < i1
  then Slice.index_usize bytes i
  else ok 0#u8

/-- [protocol::cell::push_group]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 68:4-71:5 -/
@[rust_loop_body]
def cell.push_group_loop.body
  (group : Array Std.U8 8#usize) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < cell.CELLS_PER_GROUP
  then
    let i1 ← Array.index_usize group i
    let cells1 ← alloc.vec.Vec.push cells i1
    let i2 ← i + 1#usize
    ok (cont (cells1, i2))
  else ok (done cells)

/-- [protocol::cell::push_group]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 68:4-71:5 -/
@[rust_loop]
def cell.push_group_loop
  (cells : alloc.vec.Vec Std.U8) (group : Array Std.U8 8#usize) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (cells1, i1) => cell.push_group_loop.body group cells1 i1)
    (cells, i)

/-- [protocol::cell::push_group]:
    Source: 'crates/protocol/src/cell.rs', lines 66:0-72:1 -/
@[reducible]
def cell.push_group
  (cells : alloc.vec.Vec Std.U8) (group : Array Std.U8 8#usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  cell.push_group_loop cells group 0#usize

/-- [protocol::cell::encode_cells]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop_body]
def cell.encode_cells_loop.body
  (bytes : Slice Std.U8) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let i3 ← i + 1#usize
    let i4 ← cell.byte_or_zero bytes i3
    let i5 ← i + 2#usize
    let i6 ← cell.byte_or_zero bytes i5
    let group ← cell.encode_group i2 i4 i6
    let cells1 ← cell.push_group cells group
    let i7 ← i + cell.BYTES_PER_GROUP
    ok (cont (cells1, i7))
  else ok (done cells)

/-- [protocol::cell::encode_cells]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop]
def cell.encode_cells_loop
  (bytes : Slice Std.U8) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (cells1, i1) => cell.encode_cells_loop.body bytes cells1 i1)
    (cells, i)

/-- [protocol::cell::encode_cells]:
    Source: 'crates/protocol/src/cell.rs', lines 75:0-88:1
    Visibility: public -/
@[reducible]
def cell.encode_cells
  (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  cell.encode_cells_loop bytes (alloc.vec.Vec.new Std.U8) 0#usize

/-- [protocol::cell::decode_cells]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 99:4-121:1
    Visibility: public -/
@[rust_loop_body]
def cell.decode_cells_loop.body
  (cells : Slice Std.U8) (bytes : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (Option
    (alloc.vec.Vec Std.U8)))
  := do
  let i1 := Slice.len cells
  if i < i1
  then
    let i2 ← Slice.index_usize cells i
    let i3 ← i + 1#usize
    let i4 ← Slice.index_usize cells i3
    let i5 ← i + 2#usize
    let i6 ← Slice.index_usize cells i5
    let i7 ← i + 3#usize
    let i8 ← Slice.index_usize cells i7
    let i9 ← i + 4#usize
    let i10 ← Slice.index_usize cells i9
    let i11 ← i + 5#usize
    let i12 ← Slice.index_usize cells i11
    let i13 ← i + 6#usize
    let i14 ← Slice.index_usize cells i13
    let i15 ← i + 7#usize
    let i16 ← Slice.index_usize cells i15
    let o ←
      cell.decode_group
        (Array.make 8#usize [ i2, i4, i6, i8, i10, i12, i14, i16 ])
    match o with
    | none => ok (done none)
    | some a =>
      let a1 ← Array.index_usize a 0#usize
      let b ← Array.index_usize a 1#usize
      let c ← Array.index_usize a 2#usize
      let bytes1 ← alloc.vec.Vec.push bytes a1
      let bytes2 ← alloc.vec.Vec.push bytes1 b
      let bytes3 ← alloc.vec.Vec.push bytes2 c
      let i17 ← i + cell.CELLS_PER_GROUP
      ok (cont (bytes3, i17))
  else ok (done (some bytes))

/-- [protocol::cell::decode_cells]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 99:4-121:1
    Visibility: public -/
@[rust_loop]
def cell.decode_cells_loop
  (cells : Slice Std.U8) (bytes : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  loop
    (fun (bytes1, i1) => cell.decode_cells_loop.body cells bytes1 i1)
    (bytes, i)

/-- [protocol::cell::decode_cells]:
    Source: 'crates/protocol/src/cell.rs', lines 93:0-121:1
    Visibility: public -/
def cell.decode_cells
  (cells : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let i := Slice.len cells
  let b ← core.num.Usize.is_multiple_of i cell.CELLS_PER_GROUP
  if b
  then cell.decode_cells_loop cells (alloc.vec.Vec.new Std.U8) 0#usize
  else ok none

end protocol
