-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [protocol]: function definitions
import Aeneas
import Protocol.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace protocol

/-- [protocol::ascii::push_bytes]: loop body 0:
    Source: 'crates/protocol/src/ascii.rs', lines 5:4-8:5
    Visibility: public -/
@[rust_loop_body]
def ascii.push_bytes_loop.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let out1 ← alloc.vec.Vec.push out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [protocol::ascii::push_bytes]: loop 0:
    Source: 'crates/protocol/src/ascii.rs', lines 5:4-8:5
    Visibility: public -/
@[rust_loop]
def ascii.push_bytes_loop
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => ascii.push_bytes_loop.body bytes out1 i1)
    (out, i)

/-- [protocol::ascii::push_bytes]:
    Source: 'crates/protocol/src/ascii.rs', lines 3:0-9:1
    Visibility: public -/
@[reducible]
def ascii.push_bytes
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  ascii.push_bytes_loop out bytes 0#usize

/-- [protocol::ascii::push_decimal]:
    Source: 'crates/protocol/src/ascii.rs', lines 12:0-17:1
    Visibility: public -/
def ascii.push_decimal
  (out : alloc.vec.Vec Std.U8) (n : Std.U32) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ←
    if n >= 10#u32
    then do
         let i ← n / 10#u32
         ascii.push_decimal out i
    else ok out
  let i ← n % 10#u32
  let i1 ← lift (UScalar.cast .U8 i)
  let i2 ← 48#u8 + i1
  alloc.vec.Vec.push out1 i2
partial_fixpoint

/-- [protocol::cell::BYTES_PER_GROUP]
    Source: 'crates/protocol/src/cell.rs', lines 11:0-11:37
    Visibility: public -/
@[global_simps, irreducible] def cell.BYTES_PER_GROUP : Std.Usize := 3#usize

/-- [protocol::cell::CELLS_PER_GROUP]
    Source: 'crates/protocol/src/cell.rs', lines 12:0-12:37
    Visibility: public -/
@[global_simps, irreducible] def cell.CELLS_PER_GROUP : Std.Usize := 8#usize

/-- [protocol::cell::group_bits]:
    Source: 'crates/protocol/src/cell.rs', lines 14:0-16:1 -/
def cell.group_bits
  (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result Std.U32 := do
  let i ← lift (UScalar.cast .U32 a)
  let i1 ← i <<< 16#i32
  let i2 ← lift (UScalar.cast .U32 b)
  let i3 ← i2 <<< 8#i32
  let i4 ← lift (i1 ||| i3)
  let i5 ← lift (UScalar.cast .U32 c)
  ok (i4 ||| i5)

/-- [protocol::cell::cell_at]:
    Source: 'crates/protocol/src/cell.rs', lines 18:0-20:1 -/
def cell.cell_at (bits : Std.U32) (shift : Std.U32) : Result Std.U8 := do
  let i ← bits >>> shift
  let i1 ← lift (i &&& 7#u32)
  ok (UScalar.cast .U8 i1)

/-- [protocol::cell::append_cell]:
    Source: 'crates/protocol/src/cell.rs', lines 22:0-24:1 -/
def cell.append_cell (bits : Std.U32) (cell : Std.U8) : Result Std.U32 := do
  let i ← bits <<< 3#i32
  let i1 ← lift (UScalar.cast .U32 cell)
  ok (i ||| i1)

/-- [protocol::cell::byte_at]:
    Source: 'crates/protocol/src/cell.rs', lines 26:0-28:1 -/
def cell.byte_at (bits : Std.U32) (shift : Std.U32) : Result Std.U8 := do
  let i ← bits >>> shift
  ok (UScalar.cast .U8 i)

/-- [protocol::cell::encode_group]:
    Source: 'crates/protocol/src/cell.rs', lines 32:0-44:1
    Visibility: public -/
def cell.encode_group
  (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result (Array Std.U8 8#usize) := do
  let bits ← cell.group_bits a b c
  let i ← cell.cell_at bits 21#u32
  let i1 ← cell.cell_at bits 18#u32
  let i2 ← cell.cell_at bits 15#u32
  let i3 ← cell.cell_at bits 12#u32
  let i4 ← cell.cell_at bits 9#u32
  let i5 ← cell.cell_at bits 6#u32
  let i6 ← cell.cell_at bits 3#u32
  let i7 ← cell.cell_at bits 0#u32
  ok (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ])

/-- [protocol::cell::decode_group]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 52:4-60:1
    Visibility: public -/
@[rust_loop_body]
def cell.decode_group_loop.body
  (cells : Array Std.U8 8#usize) (bits : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (Option (Array Std.U8 3#usize)))
  := do
  if i < cell.CELLS_PER_GROUP
  then
    let i1 ← Array.index_usize cells i
    if i1 > 7#u8
    then ok (done none)
    else
      let bits1 ← cell.append_cell bits i1
      let i2 ← i + 1#usize
      ok (cont (bits1, i2))
  else
    let i1 ← cell.byte_at bits 16#u32
    let i2 ← cell.byte_at bits 8#u32
    let i3 ← cell.byte_at bits 0#u32
    ok (done (some (Array.make 3#usize [ i1, i2, i3 ])))

/-- [protocol::cell::decode_group]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 52:4-60:1
    Visibility: public -/
@[rust_loop]
def cell.decode_group_loop
  (cells : Array Std.U8 8#usize) (bits : Std.U32) (i : Std.Usize) :
  Result (Option (Array Std.U8 3#usize))
  := do
  loop
    (fun (bits1, i1) => cell.decode_group_loop.body cells bits1 i1)
    (bits, i)

/-- [protocol::cell::decode_group]:
    Source: 'crates/protocol/src/cell.rs', lines 49:0-60:1
    Visibility: public -/
@[reducible]
def cell.decode_group
  (cells : Array Std.U8 8#usize) : Result (Option (Array Std.U8 3#usize)) := do
  cell.decode_group_loop cells 0#u32 0#usize

/-- [protocol::cell::byte_or_zero]:
    Source: 'crates/protocol/src/cell.rs', lines 62:0-64:1 -/
def cell.byte_or_zero
  (bytes : Slice Std.U8) (i : Std.Usize) : Result Std.U8 := do
  let i1 := Slice.len bytes
  if i < i1
  then Slice.index_usize bytes i
  else ok 0#u8

/-- [protocol::cell::push_group]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 68:4-71:5 -/
@[rust_loop_body]
def cell.push_group_loop.body
  (group : Array Std.U8 8#usize) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < cell.CELLS_PER_GROUP
  then
    let i1 ← Array.index_usize group i
    let cells1 ← alloc.vec.Vec.push cells i1
    let i2 ← i + 1#usize
    ok (cont (cells1, i2))
  else ok (done cells)

/-- [protocol::cell::push_group]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 68:4-71:5 -/
@[rust_loop]
def cell.push_group_loop
  (cells : alloc.vec.Vec Std.U8) (group : Array Std.U8 8#usize) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (cells1, i1) => cell.push_group_loop.body group cells1 i1)
    (cells, i)

/-- [protocol::cell::push_group]:
    Source: 'crates/protocol/src/cell.rs', lines 66:0-72:1 -/
@[reducible]
def cell.push_group
  (cells : alloc.vec.Vec Std.U8) (group : Array Std.U8 8#usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  cell.push_group_loop cells group 0#usize

/-- [protocol::cell::encode_cells]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop_body]
def cell.encode_cells_loop.body
  (bytes : Slice Std.U8) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let i3 ← i + 1#usize
    let i4 ← cell.byte_or_zero bytes i3
    let i5 ← i + 2#usize
    let i6 ← cell.byte_or_zero bytes i5
    let group ← cell.encode_group i2 i4 i6
    let cells1 ← cell.push_group cells group
    let i7 ← i + cell.BYTES_PER_GROUP
    ok (cont (cells1, i7))
  else ok (done cells)

/-- [protocol::cell::encode_cells]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop]
def cell.encode_cells_loop
  (bytes : Slice Std.U8) (cells : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (cells1, i1) => cell.encode_cells_loop.body bytes cells1 i1)
    (cells, i)

/-- [protocol::cell::encode_cells]:
    Source: 'crates/protocol/src/cell.rs', lines 75:0-88:1
    Visibility: public -/
@[reducible]
def cell.encode_cells
  (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  cell.encode_cells_loop bytes (alloc.vec.Vec.new Std.U8) 0#usize

/-- [protocol::cell::decode_cells]: loop body 0:
    Source: 'crates/protocol/src/cell.rs', lines 99:4-121:1
    Visibility: public -/
@[rust_loop_body]
def cell.decode_cells_loop.body
  (cells : Slice Std.U8) (bytes : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (Option
    (alloc.vec.Vec Std.U8)))
  := do
  let i1 := Slice.len cells
  if i < i1
  then
    let i2 ← Slice.index_usize cells i
    let i3 ← i + 1#usize
    let i4 ← Slice.index_usize cells i3
    let i5 ← i + 2#usize
    let i6 ← Slice.index_usize cells i5
    let i7 ← i + 3#usize
    let i8 ← Slice.index_usize cells i7
    let i9 ← i + 4#usize
    let i10 ← Slice.index_usize cells i9
    let i11 ← i + 5#usize
    let i12 ← Slice.index_usize cells i11
    let i13 ← i + 6#usize
    let i14 ← Slice.index_usize cells i13
    let i15 ← i + 7#usize
    let i16 ← Slice.index_usize cells i15
    let o ←
      cell.decode_group
        (Array.make 8#usize [ i2, i4, i6, i8, i10, i12, i14, i16 ])
    match o with
    | none => ok (done none)
    | some a =>
      let a1 ← Array.index_usize a 0#usize
      let b ← Array.index_usize a 1#usize
      let c ← Array.index_usize a 2#usize
      let bytes1 ← alloc.vec.Vec.push bytes a1
      let bytes2 ← alloc.vec.Vec.push bytes1 b
      let bytes3 ← alloc.vec.Vec.push bytes2 c
      let i17 ← i + cell.CELLS_PER_GROUP
      ok (cont (bytes3, i17))
  else ok (done (some bytes))

/-- [protocol::cell::decode_cells]: loop 0:
    Source: 'crates/protocol/src/cell.rs', lines 99:4-121:1
    Visibility: public -/
@[rust_loop]
def cell.decode_cells_loop
  (cells : Slice Std.U8) (bytes : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  loop
    (fun (bytes1, i1) => cell.decode_cells_loop.body cells bytes1 i1)
    (bytes, i)

/-- [protocol::cell::decode_cells]:
    Source: 'crates/protocol/src/cell.rs', lines 93:0-121:1
    Visibility: public -/
def cell.decode_cells
  (cells : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let i := Slice.len cells
  let b ← core.num.Usize.is_multiple_of i cell.CELLS_PER_GROUP
  if b
  then cell.decode_cells_loop cells (alloc.vec.Vec.new Std.U8) 0#usize
  else ok none

/-- [protocol::folder::resolve_folder]:
    Source: 'crates/protocol/src/folder.rs', lines 9:0-11:1
    Visibility: public -/
def folder.resolve_folder
  (roots : Slice (alloc.vec.Vec Std.U8)) (base : Slice Std.U8)
  (request : Slice Std.U8) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  fail panic

/-- [protocol::frame::MAGIC]
    Source: 'crates/protocol/src/frame.rs', lines 10:0-10:40
    Visibility: public -/
@[global_simps, irreducible]
def frame.MAGIC : Array Std.U8 2#usize := Array.make 2#usize [ 110#u8, 82#u8 ]

/-- [protocol::frame::VERSION]
    Source: 'crates/protocol/src/frame.rs', lines 11:0-11:26
    Visibility: public -/
@[global_simps, irreducible] def frame.VERSION : Std.U8 := 1#u8

/-- [protocol::frame::HEADER_LEN]
    Source: 'crates/protocol/src/frame.rs', lines 12:0-12:33
    Visibility: public -/
@[global_simps, irreducible] def frame.HEADER_LEN : Std.Usize := 11#usize

/-- [protocol::frame::CHECKSUM_LEN]
    Source: 'crates/protocol/src/frame.rs', lines 13:0-13:34
    Visibility: public -/
@[global_simps, irreducible] def frame.CHECKSUM_LEN : Std.Usize := 2#usize

/-- [protocol::frame::TAG_LEN]
    Source: 'crates/protocol/src/frame.rs', lines 14:0-14:29
    Visibility: public -/
@[global_simps, irreducible] def frame.TAG_LEN : Std.Usize := 8#usize

/-- [protocol::frame::MAX_PAYLOAD]
    Source: 'crates/protocol/src/frame.rs', lines 15:0-15:36
    Visibility: public -/
@[global_simps, irreducible] def frame.MAX_PAYLOAD : Std.Usize := 3200#usize

/-- [protocol::frame::MAX_AGE]
    Source: 'crates/protocol/src/frame.rs', lines 18:0-18:29
    Visibility: public -/
@[global_simps, irreducible] def frame.MAX_AGE : Std.U32 := 300#u32

/-- [protocol::frame::MAX_AHEAD]
    Source: 'crates/protocol/src/frame.rs', lines 19:0-19:30
    Visibility: public -/
@[global_simps, irreducible] def frame.MAX_AHEAD : Std.U32 := 60#u32

/-- [protocol::frame::encode_frame]:
    Source: 'crates/protocol/src/frame.rs', lines 46:0-48:1
    Visibility: public -/
def frame.encode_frame
  (time : Std.U32) (frame_id : Std.U16) (payload : Slice Std.U8)
  (tag : Array Std.U8 8#usize) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  fail panic

/-- [protocol::frame::decode_frame]:
    Source: 'crates/protocol/src/frame.rs', lines 51:0-53:1
    Visibility: public -/
def frame.decode_frame
  (bytes : Slice Std.U8) :
  Result (core.result.Result frame.Frame frame.FrameError)
  := do
  fail panic

/-- [protocol::frame::signed_len]:
    Source: 'crates/protocol/src/frame.rs', lines 57:0-59:1
    Visibility: public -/
def frame.signed_len (f : frame.Frame) : Result Std.Usize := do
  fail panic

/-- [protocol::frame::is_stale]:
    Source: 'crates/protocol/src/frame.rs', lines 62:0-64:1 -/
def frame.is_stale (frame_time : Std.U32) (now : Std.U32) : Result Bool := do
  let i ← lift (UScalar.cast .U64 now)
  let i1 ← lift (UScalar.cast .U64 frame_time)
  let i2 ← lift (UScalar.cast .U64 frame.MAX_AGE)
  let i3 ← i1 + i2
  ok (i > i3)

/-- [protocol::frame::is_ahead]:
    Source: 'crates/protocol/src/frame.rs', lines 66:0-68:1 -/
def frame.is_ahead (frame_time : Std.U32) (now : Std.U32) : Result Bool := do
  let i ← lift (UScalar.cast .U64 frame_time)
  let i1 ← lift (UScalar.cast .U64 now)
  let i2 ← lift (UScalar.cast .U64 frame.MAX_AHEAD)
  let i3 ← i1 + i2
  ok (i > i3)

/-- [protocol::frame::is_fresh]:
    Source: 'crates/protocol/src/frame.rs', lines 71:0-73:1
    Visibility: public -/
def frame.is_fresh (frame_time : Std.U32) (now : Std.U32) : Result Bool := do
  let b ← frame.is_stale frame_time now
  if b
  then ok false
  else let b1 ← frame.is_ahead frame_time now
       ok (¬ b1)

/-- [protocol::frame::check_frame]:
    Source: 'crates/protocol/src/frame.rs', lines 76:0-87:1
    Visibility: public -/
def frame.check_frame
  (frame_time : Std.U32) (tag_ok : Bool) (now : Std.U32) :
  Result (core.result.Result Unit frame.Reject)
  := do
  if tag_ok
  then
    let b ← frame.is_stale frame_time now
    if b
    then ok (core.result.Result.Err frame.Reject.Stale)
    else
      let b1 ← frame.is_ahead frame_time now
      if b1
      then ok (core.result.Result.Err frame.Reject.Future)
      else ok (core.result.Result.Ok ())
  else ok (core.result.Result.Err frame.Reject.BadTag)

/-- [protocol::lua::is_plain]:
    Source: 'crates/protocol/src/lua.rs', lines 4:0-6:1 -/
def lua.is_plain (b : Std.U8) : Result Bool := do
  if 32#u8 <= b
  then
    if b <= 126#u8
    then if b != 34#u8
         then ok (b != 92#u8)
         else ok false
    else ok false
  else ok false

/-- [protocol::lua::push_escape]:
    Source: 'crates/protocol/src/lua.rs', lines 9:0-14:1 -/
def lua.push_escape
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← alloc.vec.Vec.push out 92#u8
  let i ← b / 100#u8
  let i1 ← 48#u8 + i
  let out2 ← alloc.vec.Vec.push out1 i1
  let i2 ← b / 10#u8
  let i3 ← i2 % 10#u8
  let i4 ← 48#u8 + i3
  let out3 ← alloc.vec.Vec.push out2 i4
  let i5 ← b % 10#u8
  let i6 ← 48#u8 + i5
  alloc.vec.Vec.push out3 i6

/-- [protocol::lua::push_escaped]:
    Source: 'crates/protocol/src/lua.rs', lines 16:0-22:1 -/
def lua.push_escaped
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let b1 ← lua.is_plain b
  if b1
  then alloc.vec.Vec.push out b
  else lua.push_escape out b

/-- [protocol::lua::lua_string]: loop body 0:
    Source: 'crates/protocol/src/lua.rs', lines 30:4-33:5
    Visibility: public -/
@[rust_loop_body]
def lua.lua_string_loop.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let out1 ← lua.push_escaped out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [protocol::lua::lua_string]: loop 0:
    Source: 'crates/protocol/src/lua.rs', lines 30:4-33:5
    Visibility: public -/
@[rust_loop]
def lua.lua_string_loop
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => lua.lua_string_loop.body bytes out1 i1)
    (out, i)

/-- [protocol::lua::lua_string]:
    Source: 'crates/protocol/src/lua.rs', lines 26:0-36:1
    Visibility: public -/
def lua.lua_string (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) 34#u8
  let out1 ← lua.lua_string_loop bytes out 0#usize
  alloc.vec.Vec.push out1 34#u8

/-- [protocol::policy::{impl core::clone::Clone for protocol::policy::Level}::clone]:
    Source: 'crates/protocol/src/policy.rs', lines 4:9-4:14
    Visibility: public -/
def policy.Level.Insts.CoreCloneClone.clone
  (self : policy.Level) : Result policy.Level := do
  ok self

/-- Trait implementation: [protocol::policy::{impl core::clone::Clone for protocol::policy::Level}]
    Source: 'crates/protocol/src/policy.rs', lines 4:9-4:14 -/
@[reducible]
def policy.Level.Insts.CoreCloneClone : core.clone.Clone policy.Level := {
  clone := policy.Level.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [protocol::policy::{impl core::marker::Copy for protocol::policy::Level}]
    Source: 'crates/protocol/src/policy.rs', lines 4:16-4:20 -/
@[reducible]
def policy.Level.Insts.CoreMarkerCopy : core.marker.Copy policy.Level := {
  cloneInst := policy.Level.Insts.CoreCloneClone
}

/-- [protocol::policy::{impl core::clone::Clone for protocol::policy::Answer}::clone]:
    Source: 'crates/protocol/src/policy.rs', lines 12:9-12:14
    Visibility: public -/
def policy.Answer.Insts.CoreCloneClone.clone
  (self : policy.Answer) : Result policy.Answer := do
  ok self

/-- Trait implementation: [protocol::policy::{impl core::clone::Clone for protocol::policy::Answer}]
    Source: 'crates/protocol/src/policy.rs', lines 12:9-12:14 -/
@[reducible]
def policy.Answer.Insts.CoreCloneClone : core.clone.Clone policy.Answer := {
  clone := policy.Answer.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [protocol::policy::{impl core::marker::Copy for protocol::policy::Answer}]
    Source: 'crates/protocol/src/policy.rs', lines 12:16-12:20 -/
@[reducible]
def policy.Answer.Insts.CoreMarkerCopy : core.marker.Copy policy.Answer := {
  cloneInst := policy.Answer.Insts.CoreCloneClone
}

/-- [protocol::policy::rank]:
    Source: 'crates/protocol/src/policy.rs', lines 21:0-27:1 -/
def policy.rank (level : policy.Level) : Result Std.U8 := do
  match level with
  | policy.Level.Ask => ok 0#u8
  | policy.Level.AutoEdit => ok 1#u8
  | policy.Level.FullAuto => ok 2#u8

/-- [protocol::policy::effective_level]:
    Source: 'crates/protocol/src/policy.rs', lines 31:0-37:1
    Visibility: public -/
def policy.effective_level
  (config : policy.Level) (requested : policy.Level) :
  Result policy.Level
  := do
  let i ← policy.rank requested
  let i1 ← policy.rank config
  if i < i1
  then ok requested
  else ok config

/-- [protocol::policy::answer_from_game]:
    Source: 'crates/protocol/src/policy.rs', lines 41:0-46:1
    Visibility: public -/
def policy.answer_from_game
  (answer : policy.Answer) : Result policy.Answer := do
  match answer with
  | policy.Answer.AllowOnce => ok policy.Answer.AllowOnce
  | policy.Answer.AllowAlways => ok policy.Answer.AllowOnce
  | policy.Answer.RejectOnce => ok policy.Answer.RejectOnce
  | policy.Answer.RejectAlways => ok policy.Answer.RejectAlways

/-- [protocol::popup::COMMAND_BUDGET]
    Source: 'crates/protocol/src/popup.rs', lines 6:0-6:38
    Visibility: public -/
@[global_simps, irreducible] def popup.COMMAND_BUDGET : Std.Usize := 300#usize

/-- [protocol::popup::LABEL_BUDGET]
    Source: 'crates/protocol/src/popup.rs', lines 7:0-7:36
    Visibility: public -/
@[global_simps, irreducible] def popup.LABEL_BUDGET : Std.Usize := 120#usize

/-- [protocol::popup::CUT_START]
    Source: 'crates/protocol/src/popup.rs', lines 12:0-12:38 -/
@[global_simps, irreducible]
def popup.CUT_START : Array Std.U8 6#usize :=
  Array.make 6#usize [ 32#u8, 91#u8, 46#u8, 46#u8, 46#u8, 32#u8 ]

/-- [protocol::popup::CUT_END]
    Source: 'crates/protocol/src/popup.rs', lines 13:0-13:47 -/
@[global_simps, irreducible]
def popup.CUT_END : Array Std.U8 16#usize :=
  Array.make 16#usize [
    32#u8, 98#u8, 121#u8, 116#u8, 101#u8, 115#u8, 32#u8, 99#u8, 117#u8, 116#u8,
    32#u8, 46#u8, 46#u8, 46#u8, 93#u8, 32#u8
    ]

/-- [protocol::popup::AGENT_SAYS]
    Source: 'crates/protocol/src/popup.rs', lines 14:0-14:52 -/
@[global_simps, irreducible]
def popup.AGENT_SAYS : Array Std.U8 17#usize :=
  Array.make 17#usize [
    10#u8, 116#u8, 104#u8, 101#u8, 32#u8, 97#u8, 103#u8, 101#u8, 110#u8,
    116#u8, 32#u8, 115#u8, 97#u8, 121#u8, 115#u8, 58#u8, 32#u8
    ]

/-- [protocol::popup::LABEL_CUT]
    Source: 'crates/protocol/src/popup.rs', lines 15:0-15:38 -/
@[global_simps, irreducible]
def popup.LABEL_CUT : Array Std.U8 6#usize :=
  Array.make 6#usize [ 32#u8, 91#u8, 46#u8, 46#u8, 46#u8, 93#u8 ]

/-- [protocol::popup::clamp_to_u32]:
    Source: 'crates/protocol/src/popup.rs', lines 18:0-24:1 -/
def popup.clamp_to_u32 (n : Std.Usize) : Result Std.U32 := do
  let i ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if n > i
  then ok core.num.U32.MAX
  else ok (UScalar.cast .U32 n)

/-- [protocol::popup::hex_digit]:
    Source: 'crates/protocol/src/popup.rs', lines 26:0-28:1 -/
def popup.hex_digit (n : Std.U8) : Result Std.U8 := do
  if n < 10#u8
  then 48#u8 + n
  else let i ← n - 10#u8
       97#u8 + i

/-- [protocol::popup::push_shown]:
    Source: 'crates/protocol/src/popup.rs', lines 30:0-42:1 -/
def popup.push_shown
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  if b = 92#u8
  then let out1 ← alloc.vec.Vec.push out 92#u8
       alloc.vec.Vec.push out1 92#u8
  else
    if 32#u8 <= b
    then
      if b <= 126#u8
      then alloc.vec.Vec.push out b
      else
        let out1 ← alloc.vec.Vec.push out 92#u8
        let out2 ← alloc.vec.Vec.push out1 120#u8
        let i ← b / 16#u8
        let i1 ← popup.hex_digit i
        let out3 ← alloc.vec.Vec.push out2 i1
        let i2 ← b % 16#u8
        let i3 ← popup.hex_digit i2
        alloc.vec.Vec.push out3 i3
    else
      let out1 ← alloc.vec.Vec.push out 92#u8
      let out2 ← alloc.vec.Vec.push out1 120#u8
      let i ← b / 16#u8
      let i1 ← popup.hex_digit i
      let out3 ← alloc.vec.Vec.push out2 i1
      let i2 ← b % 16#u8
      let i3 ← popup.hex_digit i2
      alloc.vec.Vec.push out3 i3

/-- [protocol::popup::push_shown_range]: loop body 0:
    Source: 'crates/protocol/src/popup.rs', lines 46:4-49:5 -/
@[rust_loop_body]
def popup.push_shown_range_loop.body
  (bytes : Slice Std.U8) («end» : Std.Usize) (out : alloc.vec.Vec Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < «end»
  then
    let i1 ← Slice.index_usize bytes i
    let out1 ← popup.push_shown out i1
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [protocol::popup::push_shown_range]: loop 0:
    Source: 'crates/protocol/src/popup.rs', lines 46:4-49:5 -/
@[rust_loop]
def popup.push_shown_range_loop
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) («end» : Std.Usize)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => popup.push_shown_range_loop.body bytes «end» out1 i1)
    (out, i)

/-- [protocol::popup::push_shown_range]:
    Source: 'crates/protocol/src/popup.rs', lines 44:0-50:1 -/
@[reducible]
def popup.push_shown_range
  (out : alloc.vec.Vec Std.U8) (bytes : Slice Std.U8) (start : Std.Usize)
  («end» : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  popup.push_shown_range_loop out bytes «end» start

/-- [protocol::popup::push_command]:
    Source: 'crates/protocol/src/popup.rs', lines 52:0-64:1 -/
def popup.push_command
  (out : alloc.vec.Vec Std.U8) (command : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let n := Slice.len command
  if n <= popup.COMMAND_BUDGET
  then popup.push_shown_range out command 0#usize n
  else
    let half ← popup.COMMAND_BUDGET / 2#usize
    let out1 ← popup.push_shown_range out command 0#usize half
    let s ← lift (Array.to_slice popup.CUT_START)
    let out2 ← ascii.push_bytes out1 s
    let i ← n - popup.COMMAND_BUDGET
    let i1 ← popup.clamp_to_u32 i
    let out3 ← ascii.push_decimal out2 i1
    let s1 ← lift (Array.to_slice popup.CUT_END)
    let out4 ← ascii.push_bytes out3 s1
    let i2 ← n - half
    popup.push_shown_range out4 command i2 n

/-- [protocol::popup::push_label]:
    Source: 'crates/protocol/src/popup.rs', lines 66:0-74:1 -/
def popup.push_label
  (out : alloc.vec.Vec Std.U8) (label : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let n := Slice.len label
  if n <= popup.LABEL_BUDGET
  then popup.push_shown_range out label 0#usize n
  else
    let out1 ← popup.push_shown_range out label 0#usize popup.LABEL_BUDGET
    let s ← lift (Array.to_slice popup.LABEL_CUT)
    ascii.push_bytes out1 s

/-- [protocol::popup::popup_text]:
    Source: 'crates/protocol/src/popup.rs', lines 79:0-85:1
    Visibility: public -/
def popup.popup_text
  (command : Slice Std.U8) (label : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out ← popup.push_command (alloc.vec.Vec.new Std.U8) command
  let s ← lift (Array.to_slice popup.AGENT_SAYS)
  let out1 ← ascii.push_bytes out s
  popup.push_label out1 label

/-- [protocol::rate::MAX_MESSAGES]
    Source: 'crates/protocol/src/rate.rs', lines 3:0-3:35
    Visibility: public -/
@[global_simps, irreducible] def rate.MAX_MESSAGES : Std.Usize := 10#usize

/-- [protocol::rate::WINDOW_SECONDS]
    Source: 'crates/protocol/src/rate.rs', lines 4:0-4:35
    Visibility: public -/
@[global_simps, irreducible] def rate.WINDOW_SECONDS : Std.U32 := 60#u32

/-- [protocol::rate::MAX_QUEUE]
    Source: 'crates/protocol/src/rate.rs', lines 5:0-5:32
    Visibility: public -/
@[global_simps, irreducible] def rate.MAX_QUEUE : Std.Usize := 20#usize

/-- [protocol::rate::admit_message]:
    Source: 'crates/protocol/src/rate.rs', lines 17:0-19:1
    Visibility: public -/
def rate.admit_message
  (limiter : rate.RateLimiter) (now : Std.U32) :
  Result (Bool × rate.RateLimiter)
  := do
  fail panic

/-- [protocol::rate::enqueue]:
    Source: 'crates/protocol/src/rate.rs', lines 23:0-25:1
    Visibility: public -/
def rate.enqueue
  (queue : rate.ChatQueue) (id : Std.U32) :
  Result (Option rate.ChatQueue)
  := do
  fail panic

/-- [protocol::record::RS]
    Source: 'crates/protocol/src/record.rs', lines 7:0-7:24
    Visibility: public -/
@[global_simps, irreducible] def record.RS : Std.U8 := 30#u8

/-- [protocol::record::US]
    Source: 'crates/protocol/src/record.rs', lines 8:0-8:24
    Visibility: public -/
@[global_simps, irreducible] def record.US : Std.U8 := 31#u8

/-- [protocol::record::MAX_ID_LEN]
    Source: 'crates/protocol/src/record.rs', lines 9:0-9:33
    Visibility: public -/
@[global_simps, irreducible] def record.MAX_ID_LEN : Std.Usize := 32#usize

/-- [protocol::record::MAX_RECORDS]
    Source: 'crates/protocol/src/record.rs', lines 10:0-10:34
    Visibility: public -/
@[global_simps, irreducible] def record.MAX_RECORDS : Std.Usize := 16#usize

/-- [protocol::record::is_valid_id]:
    Source: 'crates/protocol/src/record.rs', lines 33:0-35:1
    Visibility: public -/
def record.is_valid_id (bytes : Slice Std.U8) : Result Bool := do
  fail panic

/-- [protocol::record::parse_records]:
    Source: 'crates/protocol/src/record.rs', lines 38:0-40:1
    Visibility: public -/
def record.parse_records
  (payload : Slice Std.U8) :
  Result (core.result.Result (alloc.vec.Vec record.Record) record.RecordError)
  := do
  fail panic

/-- [protocol::record::serialize_records]:
    Source: 'crates/protocol/src/record.rs', lines 43:0-45:1
    Visibility: public -/
def record.serialize_records
  (records : Slice record.Record) : Result (alloc.vec.Vec Std.U8) := do
  fail panic

/-- [protocol::seen::SEEN_CAPACITY]
    Source: 'crates/protocol/src/seen.rs', lines 3:0-3:38
    Visibility: public -/
@[global_simps, irreducible] def seen.SEEN_CAPACITY : Std.Usize := 1000#usize

/-- [protocol::seen::new_seen]:
    Source: 'crates/protocol/src/seen.rs', lines 16:0-20:1
    Visibility: public -/
def seen.new_seen : Result seen.Seen := do
  ok { entries := (alloc.vec.Vec.new seen.Entry) }

/-- [protocol::seen::admit]:
    Source: 'crates/protocol/src/seen.rs', lines 24:0-26:1
    Visibility: public -/
def seen.admit
  (history : seen.Seen) (token : Slice Std.U8) (id : Std.U32) :
  Result (Bool × seen.Seen)
  := do
  fail panic

/-- [protocol::slot::MAX_REPLIES]
    Source: 'crates/protocol/src/slot.rs', lines 3:0-3:34
    Visibility: public -/
@[global_simps, irreducible] def slot.MAX_REPLIES : Std.Usize := 30#usize

/-- [protocol::slot::MAX_TEXT]
    Source: 'crates/protocol/src/slot.rs', lines 4:0-4:38
    Visibility: public -/
@[global_simps, irreducible]
def slot.MAX_TEXT : Result Std.Usize := 32#usize * 1024#usize

/-- [protocol::slot::SLOT_BODY_LIMIT]
    Source: 'crates/protocol/src/slot.rs', lines 5:0-5:47
    Visibility: public -/
@[global_simps, irreducible]
def slot.SLOT_BODY_LIMIT : Result Std.Usize := 1024#usize * 1024#usize

/-- [protocol::slot::{impl core::clone::Clone for protocol::slot::Status}::clone]:
    Source: 'crates/protocol/src/slot.rs', lines 7:9-7:14
    Visibility: public -/
def slot.Status.Insts.CoreCloneClone.clone
  (self : slot.Status) : Result slot.Status := do
  ok self

/-- Trait implementation: [protocol::slot::{impl core::clone::Clone for protocol::slot::Status}]
    Source: 'crates/protocol/src/slot.rs', lines 7:9-7:14 -/
@[reducible]
def slot.Status.Insts.CoreCloneClone : core.clone.Clone slot.Status := {
  clone := slot.Status.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [protocol::slot::{impl core::marker::Copy for protocol::slot::Status}]
    Source: 'crates/protocol/src/slot.rs', lines 7:16-7:20 -/
@[reducible]
def slot.Status.Insts.CoreMarkerCopy : core.marker.Copy slot.Status := {
  cloneInst := slot.Status.Insts.CoreCloneClone
}

/-- [protocol::slot::prepare_replies]:
    Source: 'crates/protocol/src/slot.rs', lines 24:0-26:1
    Visibility: public -/
def slot.prepare_replies
  (replies : Slice slot.Reply) : Result (alloc.vec.Vec slot.Reply) := do
  fail panic

/-- [protocol::slot::slot_body]:
    Source: 'crates/protocol/src/slot.rs', lines 29:0-31:1
    Visibility: public -/
def slot.slot_body
  (now : Std.U32) (replies : Slice slot.Reply) :
  Result (alloc.vec.Vec Std.U8)
  := do
  fail panic

/-- [protocol::wow_text::push_safe]:
    Source: 'crates/protocol/src/wow_text.rs', lines 4:0-9:1 -/
def wow_text.push_safe
  (out : alloc.vec.Vec Std.U8) (b : Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← if b = 124#u8
               then alloc.vec.Vec.push out 124#u8
               else ok out
  alloc.vec.Vec.push out1 b

/-- [protocol::wow_text::chat_safe]: loop body 0:
    Source: 'crates/protocol/src/wow_text.rs', lines 16:4-19:5
    Visibility: public -/
@[rust_loop_body]
def wow_text.chat_safe_loop.body
  (text : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len text
  if i < i1
  then
    let i2 ← Slice.index_usize text i
    let out1 ← wow_text.push_safe out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [protocol::wow_text::chat_safe]: loop 0:
    Source: 'crates/protocol/src/wow_text.rs', lines 16:4-19:5
    Visibility: public -/
@[rust_loop]
def wow_text.chat_safe_loop
  (text : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => wow_text.chat_safe_loop.body text out1 i1)
    (out, i)

/-- [protocol::wow_text::chat_safe]:
    Source: 'crates/protocol/src/wow_text.rs', lines 13:0-21:1
    Visibility: public -/
@[reducible]
def wow_text.chat_safe
  (text : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  wow_text.chat_safe_loop text (alloc.vec.Vec.new Std.U8) 0#usize

end protocol
