-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [protocol]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace protocol

/-- [protocol::action::Verdict]
    Source: 'crates/protocol/src/action.rs', lines 14:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive action.Verdict where
| Deny : action.Verdict
| Desktop : action.Verdict
| Ask : action.Verdict
| Allow : action.Verdict

/-- [protocol::action::Policy]
    Source: 'crates/protocol/src/action.rs', lines 25:0-38:1
    Visibility: public -/
structure action.Policy where
  roots : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  chat : alloc.vec.Vec Std.U8
  deny_folders : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  desktop_paths : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  desktop_writes : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  allow : alloc.vec.Vec (alloc.vec.Vec (alloc.vec.Vec Std.U8))

/-- [protocol::action::ToolCall]
    Source: 'crates/protocol/src/action.rs', lines 40:0-50:1
    Visibility: public -/
@[discriminant isize]
inductive action.ToolCall where
| Files :
  alloc.vec.Vec (alloc.vec.Vec Std.U8) →
  alloc.vec.Vec (alloc.vec.Vec Std.U8) →
  action.ToolCall
| Command : alloc.vec.Vec Std.U8 → alloc.vec.Vec Std.U8 → action.ToolCall
| Unknown : action.ToolCall

/-- [protocol::action::Cover]
    Source: 'crates/protocol/src/action.rs', lines 54:0-57:1 -/
@[discriminant isize]
inductive action.Cover where
| Listed : action.Cover
| Every : action.Cover

/-- [protocol::shell::Access]
    Source: 'crates/protocol/src/shell.rs', lines 20:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive shell.Access where
| Read : shell.Access
| Write : shell.Access

/-- [protocol::shell::Redirect]
    Source: 'crates/protocol/src/shell.rs', lines 43:0-46:1
    Visibility: public -/
structure shell.Redirect where
  target : alloc.vec.Vec Std.U8
  access : shell.Access

/-- [protocol::folder::Walk]
    Source: 'crates/protocol/src/folder.rs', lines 13:0-17:1 -/
structure folder.Walk where
  ok : Bool
  stack : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  depth : Std.Usize

/-- [protocol::shell::Link]
    Source: 'crates/protocol/src/shell.rs', lines 29:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive shell.Link where
| First : shell.Link
| Pipe : shell.Link

/-- [protocol::shell::Simple]
    Source: 'crates/protocol/src/shell.rs', lines 36:0-39:1
    Visibility: public -/
structure shell.Simple where
  words : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  link : shell.Link

/-- [protocol::command_rules::Test]
    Source: 'crates/protocol/src/command_rules.rs', lines 46:0-55:1 -/
@[discriminant isize]
inductive command_rules.Test where
| Name : command_rules.Test
| Flag : command_rules.Test
| Recursive : command_rules.Test
| GitForce : command_rules.Test

/-- [protocol::shell::Script]
    Source: 'crates/protocol/src/shell.rs', lines 49:0-52:1
    Visibility: public -/
structure shell.Script where
  simples : alloc.vec.Vec shell.Simple
  redirects : alloc.vec.Vec shell.Redirect

/-- [protocol::shell::Pending]
    Source: 'crates/protocol/src/shell.rs', lines 67:0-73:1 -/
@[discriminant isize]
inductive shell.Pending where
| Word : shell.Pending
| Read : shell.Pending
| Write : shell.Pending
| Copy : shell.Pending

/-- [protocol::shell::Mode]
    Source: 'crates/protocol/src/shell.rs', lines 55:0-63:1 -/
@[discriminant isize]
inductive shell.Mode where
| Plain : shell.Mode
| Single : shell.Mode
| Double : shell.Mode
| DoubleEscape : shell.Mode
| Escape : shell.Mode

/-- [protocol::shell::Lexer]
    Source: 'crates/protocol/src/shell.rs', lines 75:0-89:1 -/
structure shell.Lexer where
  ok : Bool
  mode : shell.Mode
  simples : alloc.vec.Vec shell.Simple
  redirects : alloc.vec.Vec shell.Redirect
  words : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  link : shell.Link
  word : alloc.vec.Vec Std.U8
  started : Bool
  glob : Bool
  pending : shell.Pending
  depth : Std.Usize

/-- [protocol::frame::Frame]
    Source: 'crates/protocol/src/frame.rs', lines 26:0-31:1
    Visibility: public -/
structure frame.Frame where
  time : Std.U32
  frame_id : Std.U16
  payload : alloc.vec.Vec Std.U8
  tag : Array Std.U8 8#usize

/-- [protocol::frame::FrameError]
    Source: 'crates/protocol/src/frame.rs', lines 34:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive frame.FrameError where
| TooShort : frame.FrameError
| BadMagic : frame.FrameError
| BadVersion : frame.FrameError
| TooLong : frame.FrameError
| Truncated : frame.FrameError
| BadChecksum : frame.FrameError

/-- [protocol::frame::Reject]
    Source: 'crates/protocol/src/frame.rs', lines 44:0-48:1
    Visibility: public -/
@[discriminant isize]
inductive frame.Reject where
| BadTag : frame.Reject
| Stale : frame.Reject
| Future : frame.Reject

/-- [protocol::inline::Escape]
    Source: 'crates/protocol/src/inline.rs', lines 11:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive inline.Escape where
| Html : inline.Escape
| Wow : inline.Escape

/-- [protocol::inline::Mark]
    Source: 'crates/protocol/src/inline.rs', lines 17:0-20:1 -/
@[discriminant isize]
inductive inline.Mark where
| Off : inline.Mark
| On : inline.Mark

/-- [protocol::inline::Style]
    Source: 'crates/protocol/src/inline.rs', lines 23:0-26:1 -/
structure inline.Style where
  bold : inline.Mark
  italic : inline.Mark

/-- [protocol::live::Progress]
    Source: 'crates/protocol/src/live.rs', lines 19:0-23:1
    Visibility: public -/
structure live.Progress where
  chat : alloc.vec.Vec Std.U8
  id : Std.U32
  lines : alloc.vec.Vec (alloc.vec.Vec Std.U8)

/-- [protocol::live::OptionKind]
    Source: 'crates/protocol/src/live.rs', lines 26:0-31:1
    Visibility: public -/
@[discriminant isize]
inductive live.OptionKind where
| AllowOnce : live.OptionKind
| AllowAlways : live.OptionKind
| RejectOnce : live.OptionKind
| RejectAlways : live.OptionKind

/-- [protocol::live::PermOption]
    Source: 'crates/protocol/src/live.rs', lines 33:0-37:1
    Visibility: public -/
structure live.PermOption where
  id : alloc.vec.Vec Std.U8
  kind : live.OptionKind
  label : alloc.vec.Vec Std.U8

/-- [protocol::live::Request]
    Source: 'crates/protocol/src/live.rs', lines 40:0-46:1
    Visibility: public -/
structure live.Request where
  request : alloc.vec.Vec Std.U8
  chat : alloc.vec.Vec Std.U8
  id : Std.U32
  text : alloc.vec.Vec Std.U8
  options : alloc.vec.Vec live.PermOption

/-- [protocol::markdown::Open]
    Source: 'crates/protocol/src/markdown.rs', lines 29:0-34:1 -/
@[discriminant isize]
inductive markdown.Open where
| Nothing : markdown.Open
| Paragraph : markdown.Open
| Item : markdown.Open
| Quote : markdown.Open

/-- [protocol::markdown::Mode]
    Source: 'crates/protocol/src/markdown.rs', lines 38:0-41:1 -/
@[discriminant isize]
inductive markdown.Mode where
| Text : markdown.Mode
| Fence : Std.U8 → markdown.Mode

/-- [protocol::markdown::State]
    Source: 'crates/protocol/src/markdown.rs', lines 44:0-47:1 -/
structure markdown.State where
  mode : markdown.Mode
  «open» : markdown.Open

/-- [protocol::policy::Level]
    Source: 'crates/protocol/src/policy.rs', lines 6:0-10:1
    Visibility: public -/
@[discriminant isize]
inductive policy.Level where
| Ask : policy.Level
| AutoEdit : policy.Level
| FullAuto : policy.Level

/-- [protocol::policy::Answer]
    Source: 'crates/protocol/src/policy.rs', lines 14:0-19:1
    Visibility: public -/
@[discriminant isize]
inductive policy.Answer where
| AllowOnce : policy.Answer
| AllowAlways : policy.Answer
| RejectOnce : policy.Answer
| RejectAlways : policy.Answer

/-- [protocol::rate::RateLimiter]
    Source: 'crates/protocol/src/rate.rs', lines 8:0-10:1
    Visibility: public -/
structure rate.RateLimiter where
  times : alloc.vec.Vec Std.U32

/-- [protocol::rate::ChatQueue]
    Source: 'crates/protocol/src/rate.rs', lines 12:0-14:1
    Visibility: public -/
structure rate.ChatQueue where
  ids : alloc.vec.Vec Std.U32

/-- [protocol::record::Record]
    Source: 'crates/protocol/src/record.rs', lines 15:0-23:1
    Visibility: public -/
structure record.Record where
  token : alloc.vec.Vec Std.U8
  chat : alloc.vec.Vec Std.U8
  id : Std.U32
  cwd : alloc.vec.Vec Std.U8
  flags : alloc.vec.Vec Std.U8
  «name» : alloc.vec.Vec Std.U8
  text : alloc.vec.Vec Std.U8

/-- [protocol::record::RecordError]
    Source: 'crates/protocol/src/record.rs', lines 26:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive record.RecordError where
| Empty : record.RecordError
| TooMany : record.RecordError
| MissingField : record.RecordError
| BadToken : record.RecordError
| BadChat : record.RecordError
| BadId : record.RecordError

/-- [protocol::restore::Role]
    Source: 'crates/protocol/src/restore.rs', lines 16:0-20:1
    Visibility: public -/
@[discriminant isize]
inductive restore.Role where
| User : restore.Role
| Agent : restore.Role
| Error : restore.Role

/-- [protocol::restore::Entry]
    Source: 'crates/protocol/src/restore.rs', lines 22:0-26:1
    Visibility: public -/
structure restore.Entry where
  role : restore.Role
  id : Std.U32
  text : alloc.vec.Vec Std.U8

/-- [protocol::restore::Chat]
    Source: 'crates/protocol/src/restore.rs', lines 28:0-34:1
    Visibility: public -/
structure restore.Chat where
  id : alloc.vec.Vec Std.U8
  «name» : alloc.vec.Vec Std.U8
  agent : alloc.vec.Vec Std.U8
  cwd : alloc.vec.Vec Std.U8
  history : alloc.vec.Vec restore.Entry

/-- [protocol::seen::Entry]
    Source: 'crates/protocol/src/seen.rs', lines 7:0-10:1
    Visibility: public -/
structure seen.Entry where
  token : alloc.vec.Vec Std.U8
  id : Std.U32

/-- [protocol::seen::Seen]
    Source: 'crates/protocol/src/seen.rs', lines 13:0-15:1
    Visibility: public -/
structure seen.Seen where
  entries : alloc.vec.Vec seen.Entry

/-- [protocol::slot::Status]
    Source: 'crates/protocol/src/slot.rs', lines 16:0-20:1
    Visibility: public -/
@[discriminant isize]
inductive slot.Status where
| Working : slot.Status
| Done : slot.Status
| Error : slot.Status

/-- [protocol::slot::Reply]
    Source: 'crates/protocol/src/slot.rs', lines 22:0-27:1
    Visibility: public -/
structure slot.Reply where
  chat : alloc.vec.Vec Std.U8
  id : Std.U32
  status : slot.Status
  text : alloc.vec.Vec Std.U8

end protocol
