import Statements

-- scripts/check-proofs.sh reads this output. Only the three standard axioms may appear.
-- Add one line for each `check_` theorem in Statements.lean.
#print axioms Protocol.Statements.check_C1
#print axioms Protocol.Statements.check_S11_fresh
#print axioms Protocol.Statements.check_S2_S11_check
#print axioms Protocol.Statements.check_S6_level
#print axioms Protocol.Statements.check_S6_answer
#print axioms Protocol.Statements.check_S15_popup
#print axioms Protocol.Statements.check_S15_printable
#print axioms Protocol.Statements.check_S15_faithful
#print axioms Protocol.Statements.check_S8_lua_string
#print axioms Protocol.Statements.check_S8_reads_back
#print axioms Protocol.Statements.check_S10_chat_safe
#print axioms Protocol.Statements.check_C2_encode
#print axioms Protocol.Statements.check_C2_encode_too_long
#print axioms Protocol.Statements.check_C2_decode
#print axioms Protocol.Statements.check_S1_S2_decode
#print axioms Protocol.Statements.check_S2_signed_len
#print axioms Protocol.Statements.check_S13_valid_id
#print axioms Protocol.Statements.check_S3_S4_parse
#print axioms Protocol.Statements.check_C3_serialize
#print axioms Protocol.Statements.check_C3_parse
#print axioms Protocol.Statements.check_S7_seen
#print axioms Protocol.Statements.check_S14_admit
#print axioms Protocol.Statements.check_S14_window
#print axioms Protocol.Statements.check_S14_queue
#print axioms Protocol.Statements.check_S9_slot_body
#print axioms Protocol.Statements.check_S18_restore_body
#print axioms Protocol.Statements.check_S18_prepare
#print axioms Protocol.Statements.check_S19_bound
#print axioms Protocol.Statements.check_S20_live_body
#print axioms Protocol.Statements.check_S20_prepare_progress
#print axioms Protocol.Statements.check_S20_prepare_requests
#print axioms Protocol.Statements.check_S21_bound
#print axioms Protocol.Statements.check_S12_prepare
#print axioms Protocol.Statements.check_S12_bound
#print axioms Protocol.Statements.check_S5_folder
#print axioms Protocol.Statements.check_S5_folder_complete
#print axioms Protocol.Statements.check_S22_total
#print axioms Protocol.Statements.check_S23_shape
#print axioms Protocol.Statements.check_S24_escape
#print axioms Protocol.Statements.check_S25_bound
#print axioms Protocol.Statements.check_S16_paths
#print axioms Protocol.Statements.check_S16_deny
#print axioms Protocol.Statements.check_S17_ceiling
#print axioms Protocol.Statements.check_S17_unknown
#print axioms Protocol.Statements.check_S17_never_always
#print axioms Protocol.Statements.check_S27_classify
#print axioms Protocol.Statements.check_S27_ceiling
#print axioms Protocol.Statements.check_S27_split
#print axioms Protocol.Statements.check_S28_no_parse
#print axioms Protocol.Statements.check_S28_substitution
#print axioms Protocol.Statements.check_S28_desktop
#print axioms Protocol.Statements.check_S28_capped
